---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "layerdrbdvolumedefinitions.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1-25-1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              resource_name:
                type: "string"
              resource_name_suffix:
                type: "string"
              snapshot_name:
                type: "string"
              vlm_nr:
                type: "integer"
                format: "int32"
              vlm_minor_nr:
                type: "integer"
                format: "int32"
  - name: "v1-19-1"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              resource_name:
                type: "string"
              resource_name_suffix:
                type: "string"
              snapshot_name:
                type: "string"
              vlm_nr:
                type: "integer"
                format: "int32"
              vlm_minor_nr:
                type: "integer"
                format: "int32"
  - name: "v1-18-2"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              resource_name:
                type: "string"
              resource_name_suffix:
                type: "string"
              snapshot_name:
                type: "string"
              vlm_nr:
                type: "integer"
                format: "int32"
              vlm_minor_nr:
                type: "integer"
                format: "int32"
  - name: "v1-17-0"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              resource_name:
                type: "string"
              resource_name_suffix:
                type: "string"
              snapshot_name:
                type: "string"
              vlm_nr:
                type: "integer"
                format: "int32"
              vlm_minor_nr:
                type: "integer"
                format: "int32"
  - name: "v1-15-0"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              resource_name:
                type: "string"
              resource_name_suffix:
                type: "string"
              snapshot_name:
                type: "string"
              vlm_nr:
                type: "integer"
                format: "int32"
              vlm_minor_nr:
                type: "integer"
                format: "int32"
  scope: "Cluster"
  names:
    plural: "layerdrbdvolumedefinitions"
    singular: "layerdrbdvolumedefinitions"
    kind: "LayerDrbdVolumeDefinitions"
