---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "resources.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1-25-1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              node_name:
                type: "string"
              resource_name:
                type: "string"
              snapshot_name:
                type: "string"
              resource_flags:
                type: "integer"
                format: "int64"
              create_timestamp:
                type: "integer"
  - name: "v1-19-1"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              node_name:
                type: "string"
              resource_name:
                type: "string"
              snapshot_name:
                type: "string"
              resource_flags:
                type: "integer"
                format: "int64"
              create_timestamp:
                type: "integer"
  - name: "v1-18-2"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              node_name:
                type: "string"
              resource_name:
                type: "string"
              snapshot_name:
                type: "string"
              resource_flags:
                type: "integer"
                format: "int64"
              create_timestamp:
                type: "integer"
  - name: "v1-17-0"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              node_name:
                type: "string"
              resource_name:
                type: "string"
              snapshot_name:
                type: "string"
              resource_flags:
                type: "integer"
                format: "int64"
              create_timestamp:
                type: "integer"
  - name: "v1-15-0"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              node_name:
                type: "string"
              resource_name:
                type: "string"
              snapshot_name:
                type: "string"
              resource_flags:
                type: "integer"
                format: "int64"
              create_timestamp:
                type: "integer"
  scope: "Cluster"
  names:
    plural: "resources"
    singular: "resources"
    kind: "Resources"
