---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "schedules.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1-25-1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              name:
                type: "string"
              dsp_name:
                type: "string"
              flags:
                type: "integer"
                format: "int64"
              full_cron:
                type: "string"
              inc_cron:
                type: "string"
              keep_local:
                type: "integer"
                format: "int32"
              keep_remote:
                type: "integer"
                format: "int32"
              on_failure:
                type: "integer"
                format: "int64"
              max_retries:
                type: "integer"
                format: "int32"
  - name: "v1-19-1"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              name:
                type: "string"
              dsp_name:
                type: "string"
              flags:
                type: "integer"
                format: "int64"
              full_cron:
                type: "string"
              inc_cron:
                type: "string"
              keep_local:
                type: "integer"
                format: "int32"
              keep_remote:
                type: "integer"
                format: "int32"
              on_failure:
                type: "integer"
                format: "int64"
              max_retries:
                type: "integer"
                format: "int32"
  - name: "v1-18-2"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              name:
                type: "string"
              dsp_name:
                type: "string"
              flags:
                type: "integer"
                format: "int64"
              full_cron:
                type: "string"
              inc_cron:
                type: "string"
              keep_local:
                type: "integer"
                format: "int32"
              keep_remote:
                type: "integer"
                format: "int32"
              on_failure:
                type: "integer"
                format: "int64"
              max_retries:
                type: "integer"
                format: "int32"
  scope: "Cluster"
  names:
    plural: "schedules"
    singular: "schedules"
    kind: "Schedules"
