ALTER TABLE SNAPSHOT_VOLUME_DEFINITIONS ADD SNAPSHOT_FLAGS BIGINT NULL;
UPDATE SNAPSHOT_VOLUME_DEFINITIONS SET SNAPSHOT_FLAGS = 0;
ALTER TABLE SNAPSHOT_VOLUME_DEFINITIONS ALTER COLUMN SNAPSHOT_FLAGS SET NOT NULL;
