// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/MsgModNodeConn.proto

package com.linbit.linstor.proto;

public final class MsgModNodeConnOuterClass {
  private MsgModNodeConnOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgModNodeConnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.linbit.linstor.proto.MsgModNodeConn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string node_conn_uuid = 1;</code>
     */
    boolean hasNodeConnUuid();
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string node_conn_uuid = 1;</code>
     */
    java.lang.String getNodeConnUuid();
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string node_conn_uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getNodeConnUuidBytes();

    /**
     * <pre>
     * Node 1 name
     * </pre>
     *
     * <code>required string node_1_name = 2;</code>
     */
    boolean hasNode1Name();
    /**
     * <pre>
     * Node 1 name
     * </pre>
     *
     * <code>required string node_1_name = 2;</code>
     */
    java.lang.String getNode1Name();
    /**
     * <pre>
     * Node 1 name
     * </pre>
     *
     * <code>required string node_1_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNode1NameBytes();

    /**
     * <pre>
     * Node 2 name
     * </pre>
     *
     * <code>required string node_2_name = 3;</code>
     */
    boolean hasNode2Name();
    /**
     * <pre>
     * Node 2 name
     * </pre>
     *
     * <code>required string node_2_name = 3;</code>
     */
    java.lang.String getNode2Name();
    /**
     * <pre>
     * Node 2 name
     * </pre>
     *
     * <code>required string node_2_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNode2NameBytes();

    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> 
        getOverridePropsList();
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry getOverrideProps(int index);
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    int getOverridePropsCount();
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    java.util.List<? extends com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> 
        getOverridePropsOrBuilderList();
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder getOverridePropsOrBuilder(
        int index);

    /**
     * <pre>
     * Node connection property keys to delete
     * </pre>
     *
     * <code>repeated string delete_prop_keys = 5;</code>
     */
    java.util.List<java.lang.String>
        getDeletePropKeysList();
    /**
     * <pre>
     * Node connection property keys to delete
     * </pre>
     *
     * <code>repeated string delete_prop_keys = 5;</code>
     */
    int getDeletePropKeysCount();
    /**
     * <pre>
     * Node connection property keys to delete
     * </pre>
     *
     * <code>repeated string delete_prop_keys = 5;</code>
     */
    java.lang.String getDeletePropKeys(int index);
    /**
     * <pre>
     * Node connection property keys to delete
     * </pre>
     *
     * <code>repeated string delete_prop_keys = 5;</code>
     */
    com.google.protobuf.ByteString
        getDeletePropKeysBytes(int index);
  }
  /**
   * <pre>
   * linstor - Modify node connection
   * </pre>
   *
   * Protobuf type {@code com.linbit.linstor.proto.MsgModNodeConn}
   */
  public  static final class MsgModNodeConn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.linbit.linstor.proto.MsgModNodeConn)
      MsgModNodeConnOrBuilder {
    // Use MsgModNodeConn.newBuilder() to construct.
    private MsgModNodeConn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgModNodeConn() {
      nodeConnUuid_ = "";
      node1Name_ = "";
      node2Name_ = "";
      overrideProps_ = java.util.Collections.emptyList();
      deletePropKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgModNodeConn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              nodeConnUuid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              node1Name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              node2Name_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                overrideProps_ = new java.util.ArrayList<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry>();
                mutable_bitField0_ |= 0x00000008;
              }
              overrideProps_.add(
                  input.readMessage(com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                deletePropKeys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              deletePropKeys_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          overrideProps_ = java.util.Collections.unmodifiableList(overrideProps_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          deletePropKeys_ = deletePropKeys_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linbit.linstor.proto.MsgModNodeConnOuterClass.internal_static_com_linbit_linstor_proto_MsgModNodeConn_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linbit.linstor.proto.MsgModNodeConnOuterClass.internal_static_com_linbit_linstor_proto_MsgModNodeConn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn.class, com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn.Builder.class);
    }

    private int bitField0_;
    public static final int NODE_CONN_UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object nodeConnUuid_;
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string node_conn_uuid = 1;</code>
     */
    public boolean hasNodeConnUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string node_conn_uuid = 1;</code>
     */
    public java.lang.String getNodeConnUuid() {
      java.lang.Object ref = nodeConnUuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeConnUuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string node_conn_uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeConnUuidBytes() {
      java.lang.Object ref = nodeConnUuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeConnUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_1_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object node1Name_;
    /**
     * <pre>
     * Node 1 name
     * </pre>
     *
     * <code>required string node_1_name = 2;</code>
     */
    public boolean hasNode1Name() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Node 1 name
     * </pre>
     *
     * <code>required string node_1_name = 2;</code>
     */
    public java.lang.String getNode1Name() {
      java.lang.Object ref = node1Name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          node1Name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Node 1 name
     * </pre>
     *
     * <code>required string node_1_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNode1NameBytes() {
      java.lang.Object ref = node1Name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        node1Name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_2_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object node2Name_;
    /**
     * <pre>
     * Node 2 name
     * </pre>
     *
     * <code>required string node_2_name = 3;</code>
     */
    public boolean hasNode2Name() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Node 2 name
     * </pre>
     *
     * <code>required string node_2_name = 3;</code>
     */
    public java.lang.String getNode2Name() {
      java.lang.Object ref = node2Name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          node2Name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Node 2 name
     * </pre>
     *
     * <code>required string node_2_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNode2NameBytes() {
      java.lang.Object ref = node2Name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        node2Name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OVERRIDE_PROPS_FIELD_NUMBER = 4;
    private java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> overrideProps_;
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    public java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> getOverridePropsList() {
      return overrideProps_;
    }
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    public java.util.List<? extends com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> 
        getOverridePropsOrBuilderList() {
      return overrideProps_;
    }
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    public int getOverridePropsCount() {
      return overrideProps_.size();
    }
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry getOverrideProps(int index) {
      return overrideProps_.get(index);
    }
    /**
     * <pre>
     * Node connection properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
     */
    public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder getOverridePropsOrBuilder(
        int index) {
      return overrideProps_.get(index);
    }

    public static final int DELETE_PROP_KEYS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList deletePropKeys_;
    /**
     * <pre>
     * Node connection property keys to delete
     * </pre>
     *
     * <code>repeated string delete_prop_keys = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDeletePropKeysList() {
      return deletePropKeys_;
    }
    /**
     * <pre>
     * Node connection property keys to delete
     * </pre>
     *
     * <code>repeated string delete_prop_keys = 5;</code>
     */
    public int getDeletePropKeysCount() {
      return deletePropKeys_.size();
    }
    /**
     * <pre>
     * Node connection property keys to delete
     * </pre>
     *
     * <code>repeated string delete_prop_keys = 5;</code>
     */
    public java.lang.String getDeletePropKeys(int index) {
      return deletePropKeys_.get(index);
    }
    /**
     * <pre>
     * Node connection property keys to delete
     * </pre>
     *
     * <code>repeated string delete_prop_keys = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeletePropKeysBytes(int index) {
      return deletePropKeys_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNode1Name()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNode2Name()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOverridePropsCount(); i++) {
        if (!getOverrideProps(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeConnUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, node1Name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, node2Name_);
      }
      for (int i = 0; i < overrideProps_.size(); i++) {
        output.writeMessage(4, overrideProps_.get(i));
      }
      for (int i = 0; i < deletePropKeys_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deletePropKeys_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeConnUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, node1Name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, node2Name_);
      }
      for (int i = 0; i < overrideProps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, overrideProps_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < deletePropKeys_.size(); i++) {
          dataSize += computeStringSizeNoTag(deletePropKeys_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDeletePropKeysList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn)) {
        return super.equals(obj);
      }
      com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn other = (com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn) obj;

      boolean result = true;
      result = result && (hasNodeConnUuid() == other.hasNodeConnUuid());
      if (hasNodeConnUuid()) {
        result = result && getNodeConnUuid()
            .equals(other.getNodeConnUuid());
      }
      result = result && (hasNode1Name() == other.hasNode1Name());
      if (hasNode1Name()) {
        result = result && getNode1Name()
            .equals(other.getNode1Name());
      }
      result = result && (hasNode2Name() == other.hasNode2Name());
      if (hasNode2Name()) {
        result = result && getNode2Name()
            .equals(other.getNode2Name());
      }
      result = result && getOverridePropsList()
          .equals(other.getOverridePropsList());
      result = result && getDeletePropKeysList()
          .equals(other.getDeletePropKeysList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNodeConnUuid()) {
        hash = (37 * hash) + NODE_CONN_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getNodeConnUuid().hashCode();
      }
      if (hasNode1Name()) {
        hash = (37 * hash) + NODE_1_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getNode1Name().hashCode();
      }
      if (hasNode2Name()) {
        hash = (37 * hash) + NODE_2_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getNode2Name().hashCode();
      }
      if (getOverridePropsCount() > 0) {
        hash = (37 * hash) + OVERRIDE_PROPS_FIELD_NUMBER;
        hash = (53 * hash) + getOverridePropsList().hashCode();
      }
      if (getDeletePropKeysCount() > 0) {
        hash = (37 * hash) + DELETE_PROP_KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getDeletePropKeysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * linstor - Modify node connection
     * </pre>
     *
     * Protobuf type {@code com.linbit.linstor.proto.MsgModNodeConn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.linbit.linstor.proto.MsgModNodeConn)
        com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linbit.linstor.proto.MsgModNodeConnOuterClass.internal_static_com_linbit_linstor_proto_MsgModNodeConn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linbit.linstor.proto.MsgModNodeConnOuterClass.internal_static_com_linbit_linstor_proto_MsgModNodeConn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn.class, com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn.Builder.class);
      }

      // Construct using com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOverridePropsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        nodeConnUuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        node1Name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        node2Name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (overridePropsBuilder_ == null) {
          overrideProps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          overridePropsBuilder_.clear();
        }
        deletePropKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linbit.linstor.proto.MsgModNodeConnOuterClass.internal_static_com_linbit_linstor_proto_MsgModNodeConn_descriptor;
      }

      public com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn getDefaultInstanceForType() {
        return com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn.getDefaultInstance();
      }

      public com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn build() {
        com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn buildPartial() {
        com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn result = new com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeConnUuid_ = nodeConnUuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.node1Name_ = node1Name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.node2Name_ = node2Name_;
        if (overridePropsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            overrideProps_ = java.util.Collections.unmodifiableList(overrideProps_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.overrideProps_ = overrideProps_;
        } else {
          result.overrideProps_ = overridePropsBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          deletePropKeys_ = deletePropKeys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.deletePropKeys_ = deletePropKeys_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn) {
          return mergeFrom((com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn other) {
        if (other == com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn.getDefaultInstance()) return this;
        if (other.hasNodeConnUuid()) {
          bitField0_ |= 0x00000001;
          nodeConnUuid_ = other.nodeConnUuid_;
          onChanged();
        }
        if (other.hasNode1Name()) {
          bitField0_ |= 0x00000002;
          node1Name_ = other.node1Name_;
          onChanged();
        }
        if (other.hasNode2Name()) {
          bitField0_ |= 0x00000004;
          node2Name_ = other.node2Name_;
          onChanged();
        }
        if (overridePropsBuilder_ == null) {
          if (!other.overrideProps_.isEmpty()) {
            if (overrideProps_.isEmpty()) {
              overrideProps_ = other.overrideProps_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureOverridePropsIsMutable();
              overrideProps_.addAll(other.overrideProps_);
            }
            onChanged();
          }
        } else {
          if (!other.overrideProps_.isEmpty()) {
            if (overridePropsBuilder_.isEmpty()) {
              overridePropsBuilder_.dispose();
              overridePropsBuilder_ = null;
              overrideProps_ = other.overrideProps_;
              bitField0_ = (bitField0_ & ~0x00000008);
              overridePropsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOverridePropsFieldBuilder() : null;
            } else {
              overridePropsBuilder_.addAllMessages(other.overrideProps_);
            }
          }
        }
        if (!other.deletePropKeys_.isEmpty()) {
          if (deletePropKeys_.isEmpty()) {
            deletePropKeys_ = other.deletePropKeys_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDeletePropKeysIsMutable();
            deletePropKeys_.addAll(other.deletePropKeys_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNode1Name()) {
          return false;
        }
        if (!hasNode2Name()) {
          return false;
        }
        for (int i = 0; i < getOverridePropsCount(); i++) {
          if (!getOverrideProps(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeConnUuid_ = "";
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string node_conn_uuid = 1;</code>
       */
      public boolean hasNodeConnUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string node_conn_uuid = 1;</code>
       */
      public java.lang.String getNodeConnUuid() {
        java.lang.Object ref = nodeConnUuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nodeConnUuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string node_conn_uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNodeConnUuidBytes() {
        java.lang.Object ref = nodeConnUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeConnUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string node_conn_uuid = 1;</code>
       */
      public Builder setNodeConnUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeConnUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string node_conn_uuid = 1;</code>
       */
      public Builder clearNodeConnUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeConnUuid_ = getDefaultInstance().getNodeConnUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string node_conn_uuid = 1;</code>
       */
      public Builder setNodeConnUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeConnUuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object node1Name_ = "";
      /**
       * <pre>
       * Node 1 name
       * </pre>
       *
       * <code>required string node_1_name = 2;</code>
       */
      public boolean hasNode1Name() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * Node 1 name
       * </pre>
       *
       * <code>required string node_1_name = 2;</code>
       */
      public java.lang.String getNode1Name() {
        java.lang.Object ref = node1Name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            node1Name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Node 1 name
       * </pre>
       *
       * <code>required string node_1_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNode1NameBytes() {
        java.lang.Object ref = node1Name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          node1Name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Node 1 name
       * </pre>
       *
       * <code>required string node_1_name = 2;</code>
       */
      public Builder setNode1Name(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        node1Name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node 1 name
       * </pre>
       *
       * <code>required string node_1_name = 2;</code>
       */
      public Builder clearNode1Name() {
        bitField0_ = (bitField0_ & ~0x00000002);
        node1Name_ = getDefaultInstance().getNode1Name();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node 1 name
       * </pre>
       *
       * <code>required string node_1_name = 2;</code>
       */
      public Builder setNode1NameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        node1Name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object node2Name_ = "";
      /**
       * <pre>
       * Node 2 name
       * </pre>
       *
       * <code>required string node_2_name = 3;</code>
       */
      public boolean hasNode2Name() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * Node 2 name
       * </pre>
       *
       * <code>required string node_2_name = 3;</code>
       */
      public java.lang.String getNode2Name() {
        java.lang.Object ref = node2Name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            node2Name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Node 2 name
       * </pre>
       *
       * <code>required string node_2_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNode2NameBytes() {
        java.lang.Object ref = node2Name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          node2Name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Node 2 name
       * </pre>
       *
       * <code>required string node_2_name = 3;</code>
       */
      public Builder setNode2Name(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        node2Name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node 2 name
       * </pre>
       *
       * <code>required string node_2_name = 3;</code>
       */
      public Builder clearNode2Name() {
        bitField0_ = (bitField0_ & ~0x00000004);
        node2Name_ = getDefaultInstance().getNode2Name();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node 2 name
       * </pre>
       *
       * <code>required string node_2_name = 3;</code>
       */
      public Builder setNode2NameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        node2Name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> overrideProps_ =
        java.util.Collections.emptyList();
      private void ensureOverridePropsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          overrideProps_ = new java.util.ArrayList<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry>(overrideProps_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> overridePropsBuilder_;

      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> getOverridePropsList() {
        if (overridePropsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(overrideProps_);
        } else {
          return overridePropsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public int getOverridePropsCount() {
        if (overridePropsBuilder_ == null) {
          return overrideProps_.size();
        } else {
          return overridePropsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry getOverrideProps(int index) {
        if (overridePropsBuilder_ == null) {
          return overrideProps_.get(index);
        } else {
          return overridePropsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder setOverrideProps(
          int index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry value) {
        if (overridePropsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOverridePropsIsMutable();
          overrideProps_.set(index, value);
          onChanged();
        } else {
          overridePropsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder setOverrideProps(
          int index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder builderForValue) {
        if (overridePropsBuilder_ == null) {
          ensureOverridePropsIsMutable();
          overrideProps_.set(index, builderForValue.build());
          onChanged();
        } else {
          overridePropsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder addOverrideProps(com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry value) {
        if (overridePropsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOverridePropsIsMutable();
          overrideProps_.add(value);
          onChanged();
        } else {
          overridePropsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder addOverrideProps(
          int index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry value) {
        if (overridePropsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOverridePropsIsMutable();
          overrideProps_.add(index, value);
          onChanged();
        } else {
          overridePropsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder addOverrideProps(
          com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder builderForValue) {
        if (overridePropsBuilder_ == null) {
          ensureOverridePropsIsMutable();
          overrideProps_.add(builderForValue.build());
          onChanged();
        } else {
          overridePropsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder addOverrideProps(
          int index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder builderForValue) {
        if (overridePropsBuilder_ == null) {
          ensureOverridePropsIsMutable();
          overrideProps_.add(index, builderForValue.build());
          onChanged();
        } else {
          overridePropsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder addAllOverrideProps(
          java.lang.Iterable<? extends com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> values) {
        if (overridePropsBuilder_ == null) {
          ensureOverridePropsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, overrideProps_);
          onChanged();
        } else {
          overridePropsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder clearOverrideProps() {
        if (overridePropsBuilder_ == null) {
          overrideProps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          overridePropsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public Builder removeOverrideProps(int index) {
        if (overridePropsBuilder_ == null) {
          ensureOverridePropsIsMutable();
          overrideProps_.remove(index);
          onChanged();
        } else {
          overridePropsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder getOverridePropsBuilder(
          int index) {
        return getOverridePropsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder getOverridePropsOrBuilder(
          int index) {
        if (overridePropsBuilder_ == null) {
          return overrideProps_.get(index);  } else {
          return overridePropsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public java.util.List<? extends com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> 
           getOverridePropsOrBuilderList() {
        if (overridePropsBuilder_ != null) {
          return overridePropsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(overrideProps_);
        }
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder addOverridePropsBuilder() {
        return getOverridePropsFieldBuilder().addBuilder(
            com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.getDefaultInstance());
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder addOverridePropsBuilder(
          int index) {
        return getOverridePropsFieldBuilder().addBuilder(
            index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.getDefaultInstance());
      }
      /**
       * <pre>
       * Node connection properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry override_props = 4;</code>
       */
      public java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder> 
           getOverridePropsBuilderList() {
        return getOverridePropsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> 
          getOverridePropsFieldBuilder() {
        if (overridePropsBuilder_ == null) {
          overridePropsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder>(
                  overrideProps_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          overrideProps_ = null;
        }
        return overridePropsBuilder_;
      }

      private com.google.protobuf.LazyStringList deletePropKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDeletePropKeysIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          deletePropKeys_ = new com.google.protobuf.LazyStringArrayList(deletePropKeys_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDeletePropKeysList() {
        return deletePropKeys_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public int getDeletePropKeysCount() {
        return deletePropKeys_.size();
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public java.lang.String getDeletePropKeys(int index) {
        return deletePropKeys_.get(index);
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDeletePropKeysBytes(int index) {
        return deletePropKeys_.getByteString(index);
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public Builder setDeletePropKeys(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeletePropKeysIsMutable();
        deletePropKeys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public Builder addDeletePropKeys(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeletePropKeysIsMutable();
        deletePropKeys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public Builder addAllDeletePropKeys(
          java.lang.Iterable<java.lang.String> values) {
        ensureDeletePropKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deletePropKeys_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public Builder clearDeletePropKeys() {
        deletePropKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node connection property keys to delete
       * </pre>
       *
       * <code>repeated string delete_prop_keys = 5;</code>
       */
      public Builder addDeletePropKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDeletePropKeysIsMutable();
        deletePropKeys_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.linbit.linstor.proto.MsgModNodeConn)
    }

    // @@protoc_insertion_point(class_scope:com.linbit.linstor.proto.MsgModNodeConn)
    private static final com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn();
    }

    public static com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MsgModNodeConn>
        PARSER = new com.google.protobuf.AbstractParser<MsgModNodeConn>() {
      public MsgModNodeConn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgModNodeConn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgModNodeConn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgModNodeConn> getParserForType() {
      return PARSER;
    }

    public com.linbit.linstor.proto.MsgModNodeConnOuterClass.MsgModNodeConn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_linstor_proto_MsgModNodeConn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_linstor_proto_MsgModNodeConn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/MsgModNodeConn.proto\022\030com.linbit" +
      ".linstor.proto\032\033proto/LinStorMapEntry.pr" +
      "oto\"\257\001\n\016MsgModNodeConn\022\026\n\016node_conn_uuid" +
      "\030\001 \001(\t\022\023\n\013node_1_name\030\002 \002(\t\022\023\n\013node_2_na" +
      "me\030\003 \002(\t\022A\n\016override_props\030\004 \003(\0132).com.l" +
      "inbit.linstor.proto.LinStorMapEntry\022\030\n\020d" +
      "elete_prop_keys\030\005 \003(\tP\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.linbit.linstor.proto.LinStorMapEntryOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_linbit_linstor_proto_MsgModNodeConn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_linbit_linstor_proto_MsgModNodeConn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_linstor_proto_MsgModNodeConn_descriptor,
        new java.lang.String[] { "NodeConnUuid", "Node1Name", "Node2Name", "OverrideProps", "DeletePropKeys", });
    com.linbit.linstor.proto.LinStorMapEntryOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
