// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Node.proto

package com.linbit.linstor.proto;

public final class NodeOuterClass {
  private NodeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.linbit.linstor.proto.Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Node type
     * </pre>
     *
     * <code>required string type = 3;</code>
     */
    boolean hasType();
    /**
     * <pre>
     * Node type
     * </pre>
     *
     * <code>required string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <pre>
     * Node type
     * </pre>
     *
     * <code>required string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> 
        getPropsList();
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry getProps(int index);
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    int getPropsCount();
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    java.util.List<? extends com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> 
        getPropsOrBuilderList();
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder getPropsOrBuilder(
        int index);

    /**
     * <pre>
     * Node flags
     * </pre>
     *
     * <code>repeated string flags = 5;</code>
     */
    java.util.List<java.lang.String>
        getFlagsList();
    /**
     * <pre>
     * Node flags
     * </pre>
     *
     * <code>repeated string flags = 5;</code>
     */
    int getFlagsCount();
    /**
     * <pre>
     * Node flags
     * </pre>
     *
     * <code>repeated string flags = 5;</code>
     */
    java.lang.String getFlags(int index);
    /**
     * <pre>
     * Node flags
     * </pre>
     *
     * <code>repeated string flags = 5;</code>
     */
    com.google.protobuf.ByteString
        getFlagsBytes(int index);

    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    java.util.List<com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface> 
        getNetInterfacesList();
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface getNetInterfaces(int index);
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    int getNetInterfacesCount();
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    java.util.List<? extends com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder> 
        getNetInterfacesOrBuilderList();
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder getNetInterfacesOrBuilder(
        int index);

    /**
     * <pre>
     * Node connected
     * </pre>
     *
     * <code>optional bool connected = 7;</code>
     */
    boolean hasConnected();
    /**
     * <pre>
     * Node connected
     * </pre>
     *
     * <code>optional bool connected = 7;</code>
     */
    boolean getConnected();

    /**
     * <pre>
     * Node's diskless stor pool uuid
     * </pre>
     *
     * <code>optional string diskless_stor_pool_uuid = 8;</code>
     */
    boolean hasDisklessStorPoolUuid();
    /**
     * <pre>
     * Node's diskless stor pool uuid
     * </pre>
     *
     * <code>optional string diskless_stor_pool_uuid = 8;</code>
     */
    java.lang.String getDisklessStorPoolUuid();
    /**
     * <pre>
     * Node's diskless stor pool uuid
     * </pre>
     *
     * <code>optional string diskless_stor_pool_uuid = 8;</code>
     */
    com.google.protobuf.ByteString
        getDisklessStorPoolUuidBytes();
  }
  /**
   * Protobuf type {@code com.linbit.linstor.proto.Node}
   */
  public  static final class Node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.linbit.linstor.proto.Node)
      NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Node() {
      uuid_ = "";
      name_ = "";
      type_ = "";
      props_ = java.util.Collections.emptyList();
      flags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      netInterfaces_ = java.util.Collections.emptyList();
      connected_ = false;
      disklessStorPoolUuid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              type_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                props_ = new java.util.ArrayList<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry>();
                mutable_bitField0_ |= 0x00000008;
              }
              props_.add(
                  input.readMessage(com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                flags_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              flags_.add(bs);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                netInterfaces_ = new java.util.ArrayList<com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface>();
                mutable_bitField0_ |= 0x00000020;
              }
              netInterfaces_.add(
                  input.readMessage(com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.PARSER, extensionRegistry));
              break;
            }
            case 56: {
              bitField0_ |= 0x00000008;
              connected_ = input.readBool();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              disklessStorPoolUuid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          props_ = java.util.Collections.unmodifiableList(props_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          flags_ = flags_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          netInterfaces_ = java.util.Collections.unmodifiableList(netInterfaces_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linbit.linstor.proto.NodeOuterClass.internal_static_com_linbit_linstor_proto_Node_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linbit.linstor.proto.NodeOuterClass.internal_static_com_linbit_linstor_proto_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linbit.linstor.proto.NodeOuterClass.Node.class, com.linbit.linstor.proto.NodeOuterClass.Node.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string uuid = 1;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * UUID
     * </pre>
     *
     * <code>optional string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     * Node type
     * </pre>
     *
     * <code>required string type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Node type
     * </pre>
     *
     * <code>required string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Node type
     * </pre>
     *
     * <code>required string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPS_FIELD_NUMBER = 4;
    private java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> props_;
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    public java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> getPropsList() {
      return props_;
    }
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    public java.util.List<? extends com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> 
        getPropsOrBuilderList() {
      return props_;
    }
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    public int getPropsCount() {
      return props_.size();
    }
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry getProps(int index) {
      return props_.get(index);
    }
    /**
     * <pre>
     * Node properties map
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
     */
    public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder getPropsOrBuilder(
        int index) {
      return props_.get(index);
    }

    public static final int FLAGS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList flags_;
    /**
     * <pre>
     * Node flags
     * </pre>
     *
     * <code>repeated string flags = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFlagsList() {
      return flags_;
    }
    /**
     * <pre>
     * Node flags
     * </pre>
     *
     * <code>repeated string flags = 5;</code>
     */
    public int getFlagsCount() {
      return flags_.size();
    }
    /**
     * <pre>
     * Node flags
     * </pre>
     *
     * <code>repeated string flags = 5;</code>
     */
    public java.lang.String getFlags(int index) {
      return flags_.get(index);
    }
    /**
     * <pre>
     * Node flags
     * </pre>
     *
     * <code>repeated string flags = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFlagsBytes(int index) {
      return flags_.getByteString(index);
    }

    public static final int NET_INTERFACES_FIELD_NUMBER = 6;
    private java.util.List<com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface> netInterfaces_;
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    public java.util.List<com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface> getNetInterfacesList() {
      return netInterfaces_;
    }
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    public java.util.List<? extends com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder> 
        getNetInterfacesOrBuilderList() {
      return netInterfaces_;
    }
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    public int getNetInterfacesCount() {
      return netInterfaces_.size();
    }
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    public com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface getNetInterfaces(int index) {
      return netInterfaces_.get(index);
    }
    /**
     * <pre>
     * NetInterfaces
     * </pre>
     *
     * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
     */
    public com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder getNetInterfacesOrBuilder(
        int index) {
      return netInterfaces_.get(index);
    }

    public static final int CONNECTED_FIELD_NUMBER = 7;
    private boolean connected_;
    /**
     * <pre>
     * Node connected
     * </pre>
     *
     * <code>optional bool connected = 7;</code>
     */
    public boolean hasConnected() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * Node connected
     * </pre>
     *
     * <code>optional bool connected = 7;</code>
     */
    public boolean getConnected() {
      return connected_;
    }

    public static final int DISKLESS_STOR_POOL_UUID_FIELD_NUMBER = 8;
    private volatile java.lang.Object disklessStorPoolUuid_;
    /**
     * <pre>
     * Node's diskless stor pool uuid
     * </pre>
     *
     * <code>optional string diskless_stor_pool_uuid = 8;</code>
     */
    public boolean hasDisklessStorPoolUuid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * Node's diskless stor pool uuid
     * </pre>
     *
     * <code>optional string diskless_stor_pool_uuid = 8;</code>
     */
    public java.lang.String getDisklessStorPoolUuid() {
      java.lang.Object ref = disklessStorPoolUuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          disklessStorPoolUuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Node's diskless stor pool uuid
     * </pre>
     *
     * <code>optional string diskless_stor_pool_uuid = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDisklessStorPoolUuidBytes() {
      java.lang.Object ref = disklessStorPoolUuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        disklessStorPoolUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropsCount(); i++) {
        if (!getProps(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getNetInterfacesCount(); i++) {
        if (!getNetInterfaces(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      for (int i = 0; i < props_.size(); i++) {
        output.writeMessage(4, props_.get(i));
      }
      for (int i = 0; i < flags_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, flags_.getRaw(i));
      }
      for (int i = 0; i < netInterfaces_.size(); i++) {
        output.writeMessage(6, netInterfaces_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(7, connected_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, disklessStorPoolUuid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      for (int i = 0; i < props_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, props_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < flags_.size(); i++) {
          dataSize += computeStringSizeNoTag(flags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFlagsList().size();
      }
      for (int i = 0; i < netInterfaces_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, netInterfaces_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, connected_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, disklessStorPoolUuid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linbit.linstor.proto.NodeOuterClass.Node)) {
        return super.equals(obj);
      }
      com.linbit.linstor.proto.NodeOuterClass.Node other = (com.linbit.linstor.proto.NodeOuterClass.Node) obj;

      boolean result = true;
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && getPropsList()
          .equals(other.getPropsList());
      result = result && getFlagsList()
          .equals(other.getFlagsList());
      result = result && getNetInterfacesList()
          .equals(other.getNetInterfacesList());
      result = result && (hasConnected() == other.hasConnected());
      if (hasConnected()) {
        result = result && (getConnected()
            == other.getConnected());
      }
      result = result && (hasDisklessStorPoolUuid() == other.hasDisklessStorPoolUuid());
      if (hasDisklessStorPoolUuid()) {
        result = result && getDisklessStorPoolUuid()
            .equals(other.getDisklessStorPoolUuid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (getPropsCount() > 0) {
        hash = (37 * hash) + PROPS_FIELD_NUMBER;
        hash = (53 * hash) + getPropsList().hashCode();
      }
      if (getFlagsCount() > 0) {
        hash = (37 * hash) + FLAGS_FIELD_NUMBER;
        hash = (53 * hash) + getFlagsList().hashCode();
      }
      if (getNetInterfacesCount() > 0) {
        hash = (37 * hash) + NET_INTERFACES_FIELD_NUMBER;
        hash = (53 * hash) + getNetInterfacesList().hashCode();
      }
      if (hasConnected()) {
        hash = (37 * hash) + CONNECTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getConnected());
      }
      if (hasDisklessStorPoolUuid()) {
        hash = (37 * hash) + DISKLESS_STOR_POOL_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getDisklessStorPoolUuid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linbit.linstor.proto.NodeOuterClass.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.NodeOuterClass.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linbit.linstor.proto.NodeOuterClass.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.linbit.linstor.proto.Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.linbit.linstor.proto.Node)
        com.linbit.linstor.proto.NodeOuterClass.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linbit.linstor.proto.NodeOuterClass.internal_static_com_linbit_linstor_proto_Node_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linbit.linstor.proto.NodeOuterClass.internal_static_com_linbit_linstor_proto_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linbit.linstor.proto.NodeOuterClass.Node.class, com.linbit.linstor.proto.NodeOuterClass.Node.Builder.class);
      }

      // Construct using com.linbit.linstor.proto.NodeOuterClass.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPropsFieldBuilder();
          getNetInterfacesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (propsBuilder_ == null) {
          props_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          propsBuilder_.clear();
        }
        flags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (netInterfacesBuilder_ == null) {
          netInterfaces_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          netInterfacesBuilder_.clear();
        }
        connected_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        disklessStorPoolUuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linbit.linstor.proto.NodeOuterClass.internal_static_com_linbit_linstor_proto_Node_descriptor;
      }

      public com.linbit.linstor.proto.NodeOuterClass.Node getDefaultInstanceForType() {
        return com.linbit.linstor.proto.NodeOuterClass.Node.getDefaultInstance();
      }

      public com.linbit.linstor.proto.NodeOuterClass.Node build() {
        com.linbit.linstor.proto.NodeOuterClass.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linbit.linstor.proto.NodeOuterClass.Node buildPartial() {
        com.linbit.linstor.proto.NodeOuterClass.Node result = new com.linbit.linstor.proto.NodeOuterClass.Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (propsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            props_ = java.util.Collections.unmodifiableList(props_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.props_ = props_;
        } else {
          result.props_ = propsBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          flags_ = flags_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.flags_ = flags_;
        if (netInterfacesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            netInterfaces_ = java.util.Collections.unmodifiableList(netInterfaces_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.netInterfaces_ = netInterfaces_;
        } else {
          result.netInterfaces_ = netInterfacesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000008;
        }
        result.connected_ = connected_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000010;
        }
        result.disklessStorPoolUuid_ = disklessStorPoolUuid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linbit.linstor.proto.NodeOuterClass.Node) {
          return mergeFrom((com.linbit.linstor.proto.NodeOuterClass.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linbit.linstor.proto.NodeOuterClass.Node other) {
        if (other == com.linbit.linstor.proto.NodeOuterClass.Node.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (propsBuilder_ == null) {
          if (!other.props_.isEmpty()) {
            if (props_.isEmpty()) {
              props_ = other.props_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePropsIsMutable();
              props_.addAll(other.props_);
            }
            onChanged();
          }
        } else {
          if (!other.props_.isEmpty()) {
            if (propsBuilder_.isEmpty()) {
              propsBuilder_.dispose();
              propsBuilder_ = null;
              props_ = other.props_;
              bitField0_ = (bitField0_ & ~0x00000008);
              propsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPropsFieldBuilder() : null;
            } else {
              propsBuilder_.addAllMessages(other.props_);
            }
          }
        }
        if (!other.flags_.isEmpty()) {
          if (flags_.isEmpty()) {
            flags_ = other.flags_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureFlagsIsMutable();
            flags_.addAll(other.flags_);
          }
          onChanged();
        }
        if (netInterfacesBuilder_ == null) {
          if (!other.netInterfaces_.isEmpty()) {
            if (netInterfaces_.isEmpty()) {
              netInterfaces_ = other.netInterfaces_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureNetInterfacesIsMutable();
              netInterfaces_.addAll(other.netInterfaces_);
            }
            onChanged();
          }
        } else {
          if (!other.netInterfaces_.isEmpty()) {
            if (netInterfacesBuilder_.isEmpty()) {
              netInterfacesBuilder_.dispose();
              netInterfacesBuilder_ = null;
              netInterfaces_ = other.netInterfaces_;
              bitField0_ = (bitField0_ & ~0x00000020);
              netInterfacesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNetInterfacesFieldBuilder() : null;
            } else {
              netInterfacesBuilder_.addAllMessages(other.netInterfaces_);
            }
          }
        }
        if (other.hasConnected()) {
          setConnected(other.getConnected());
        }
        if (other.hasDisklessStorPoolUuid()) {
          bitField0_ |= 0x00000080;
          disklessStorPoolUuid_ = other.disklessStorPoolUuid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        for (int i = 0; i < getPropsCount(); i++) {
          if (!getProps(i).isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getNetInterfacesCount(); i++) {
          if (!getNetInterfaces(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linbit.linstor.proto.NodeOuterClass.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linbit.linstor.proto.NodeOuterClass.Node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string uuid = 1;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UUID
       * </pre>
       *
       * <code>optional string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * Node type
       * </pre>
       *
       * <code>required string type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * Node type
       * </pre>
       *
       * <code>required string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Node type
       * </pre>
       *
       * <code>required string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Node type
       * </pre>
       *
       * <code>required string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node type
       * </pre>
       *
       * <code>required string type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node type
       * </pre>
       *
       * <code>required string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> props_ =
        java.util.Collections.emptyList();
      private void ensurePropsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          props_ = new java.util.ArrayList<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry>(props_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> propsBuilder_;

      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> getPropsList() {
        if (propsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(props_);
        } else {
          return propsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public int getPropsCount() {
        if (propsBuilder_ == null) {
          return props_.size();
        } else {
          return propsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry getProps(int index) {
        if (propsBuilder_ == null) {
          return props_.get(index);
        } else {
          return propsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder setProps(
          int index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry value) {
        if (propsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropsIsMutable();
          props_.set(index, value);
          onChanged();
        } else {
          propsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder setProps(
          int index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder builderForValue) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          props_.set(index, builderForValue.build());
          onChanged();
        } else {
          propsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder addProps(com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry value) {
        if (propsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropsIsMutable();
          props_.add(value);
          onChanged();
        } else {
          propsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder addProps(
          int index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry value) {
        if (propsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropsIsMutable();
          props_.add(index, value);
          onChanged();
        } else {
          propsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder addProps(
          com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder builderForValue) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          props_.add(builderForValue.build());
          onChanged();
        } else {
          propsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder addProps(
          int index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder builderForValue) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          props_.add(index, builderForValue.build());
          onChanged();
        } else {
          propsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder addAllProps(
          java.lang.Iterable<? extends com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry> values) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, props_);
          onChanged();
        } else {
          propsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder clearProps() {
        if (propsBuilder_ == null) {
          props_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          propsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public Builder removeProps(int index) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          props_.remove(index);
          onChanged();
        } else {
          propsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder getPropsBuilder(
          int index) {
        return getPropsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder getPropsOrBuilder(
          int index) {
        if (propsBuilder_ == null) {
          return props_.get(index);  } else {
          return propsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public java.util.List<? extends com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> 
           getPropsOrBuilderList() {
        if (propsBuilder_ != null) {
          return propsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(props_);
        }
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder addPropsBuilder() {
        return getPropsFieldBuilder().addBuilder(
            com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.getDefaultInstance());
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder addPropsBuilder(
          int index) {
        return getPropsFieldBuilder().addBuilder(
            index, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.getDefaultInstance());
      }
      /**
       * <pre>
       * Node properties map
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.LinStorMapEntry props = 4;</code>
       */
      public java.util.List<com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder> 
           getPropsBuilderList() {
        return getPropsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder> 
          getPropsFieldBuilder() {
        if (propsBuilder_ == null) {
          propsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntry.Builder, com.linbit.linstor.proto.LinStorMapEntryOuterClass.LinStorMapEntryOrBuilder>(
                  props_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          props_ = null;
        }
        return propsBuilder_;
      }

      private com.google.protobuf.LazyStringList flags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFlagsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          flags_ = new com.google.protobuf.LazyStringArrayList(flags_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFlagsList() {
        return flags_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public int getFlagsCount() {
        return flags_.size();
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public java.lang.String getFlags(int index) {
        return flags_.get(index);
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFlagsBytes(int index) {
        return flags_.getByteString(index);
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public Builder setFlags(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFlagsIsMutable();
        flags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public Builder addFlags(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFlagsIsMutable();
        flags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public Builder addAllFlags(
          java.lang.Iterable<java.lang.String> values) {
        ensureFlagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, flags_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public Builder clearFlags() {
        flags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node flags
       * </pre>
       *
       * <code>repeated string flags = 5;</code>
       */
      public Builder addFlagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFlagsIsMutable();
        flags_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface> netInterfaces_ =
        java.util.Collections.emptyList();
      private void ensureNetInterfacesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          netInterfaces_ = new java.util.ArrayList<com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface>(netInterfaces_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder> netInterfacesBuilder_;

      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public java.util.List<com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface> getNetInterfacesList() {
        if (netInterfacesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(netInterfaces_);
        } else {
          return netInterfacesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public int getNetInterfacesCount() {
        if (netInterfacesBuilder_ == null) {
          return netInterfaces_.size();
        } else {
          return netInterfacesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface getNetInterfaces(int index) {
        if (netInterfacesBuilder_ == null) {
          return netInterfaces_.get(index);
        } else {
          return netInterfacesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder setNetInterfaces(
          int index, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface value) {
        if (netInterfacesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetInterfacesIsMutable();
          netInterfaces_.set(index, value);
          onChanged();
        } else {
          netInterfacesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder setNetInterfaces(
          int index, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder builderForValue) {
        if (netInterfacesBuilder_ == null) {
          ensureNetInterfacesIsMutable();
          netInterfaces_.set(index, builderForValue.build());
          onChanged();
        } else {
          netInterfacesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder addNetInterfaces(com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface value) {
        if (netInterfacesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetInterfacesIsMutable();
          netInterfaces_.add(value);
          onChanged();
        } else {
          netInterfacesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder addNetInterfaces(
          int index, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface value) {
        if (netInterfacesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetInterfacesIsMutable();
          netInterfaces_.add(index, value);
          onChanged();
        } else {
          netInterfacesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder addNetInterfaces(
          com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder builderForValue) {
        if (netInterfacesBuilder_ == null) {
          ensureNetInterfacesIsMutable();
          netInterfaces_.add(builderForValue.build());
          onChanged();
        } else {
          netInterfacesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder addNetInterfaces(
          int index, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder builderForValue) {
        if (netInterfacesBuilder_ == null) {
          ensureNetInterfacesIsMutable();
          netInterfaces_.add(index, builderForValue.build());
          onChanged();
        } else {
          netInterfacesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder addAllNetInterfaces(
          java.lang.Iterable<? extends com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface> values) {
        if (netInterfacesBuilder_ == null) {
          ensureNetInterfacesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, netInterfaces_);
          onChanged();
        } else {
          netInterfacesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder clearNetInterfaces() {
        if (netInterfacesBuilder_ == null) {
          netInterfaces_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          netInterfacesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public Builder removeNetInterfaces(int index) {
        if (netInterfacesBuilder_ == null) {
          ensureNetInterfacesIsMutable();
          netInterfaces_.remove(index);
          onChanged();
        } else {
          netInterfacesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder getNetInterfacesBuilder(
          int index) {
        return getNetInterfacesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder getNetInterfacesOrBuilder(
          int index) {
        if (netInterfacesBuilder_ == null) {
          return netInterfaces_.get(index);  } else {
          return netInterfacesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public java.util.List<? extends com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder> 
           getNetInterfacesOrBuilderList() {
        if (netInterfacesBuilder_ != null) {
          return netInterfacesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(netInterfaces_);
        }
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder addNetInterfacesBuilder() {
        return getNetInterfacesFieldBuilder().addBuilder(
            com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.getDefaultInstance());
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder addNetInterfacesBuilder(
          int index) {
        return getNetInterfacesFieldBuilder().addBuilder(
            index, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.getDefaultInstance());
      }
      /**
       * <pre>
       * NetInterfaces
       * </pre>
       *
       * <code>repeated .com.linbit.linstor.proto.NetInterface net_interfaces = 6;</code>
       */
      public java.util.List<com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder> 
           getNetInterfacesBuilderList() {
        return getNetInterfacesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder> 
          getNetInterfacesFieldBuilder() {
        if (netInterfacesBuilder_ == null) {
          netInterfacesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterface.Builder, com.linbit.linstor.proto.NetInterfaceOuterClass.NetInterfaceOrBuilder>(
                  netInterfaces_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          netInterfaces_ = null;
        }
        return netInterfacesBuilder_;
      }

      private boolean connected_ ;
      /**
       * <pre>
       * Node connected
       * </pre>
       *
       * <code>optional bool connected = 7;</code>
       */
      public boolean hasConnected() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * Node connected
       * </pre>
       *
       * <code>optional bool connected = 7;</code>
       */
      public boolean getConnected() {
        return connected_;
      }
      /**
       * <pre>
       * Node connected
       * </pre>
       *
       * <code>optional bool connected = 7;</code>
       */
      public Builder setConnected(boolean value) {
        bitField0_ |= 0x00000040;
        connected_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node connected
       * </pre>
       *
       * <code>optional bool connected = 7;</code>
       */
      public Builder clearConnected() {
        bitField0_ = (bitField0_ & ~0x00000040);
        connected_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object disklessStorPoolUuid_ = "";
      /**
       * <pre>
       * Node's diskless stor pool uuid
       * </pre>
       *
       * <code>optional string diskless_stor_pool_uuid = 8;</code>
       */
      public boolean hasDisklessStorPoolUuid() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * Node's diskless stor pool uuid
       * </pre>
       *
       * <code>optional string diskless_stor_pool_uuid = 8;</code>
       */
      public java.lang.String getDisklessStorPoolUuid() {
        java.lang.Object ref = disklessStorPoolUuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            disklessStorPoolUuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Node's diskless stor pool uuid
       * </pre>
       *
       * <code>optional string diskless_stor_pool_uuid = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDisklessStorPoolUuidBytes() {
        java.lang.Object ref = disklessStorPoolUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          disklessStorPoolUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Node's diskless stor pool uuid
       * </pre>
       *
       * <code>optional string diskless_stor_pool_uuid = 8;</code>
       */
      public Builder setDisklessStorPoolUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        disklessStorPoolUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node's diskless stor pool uuid
       * </pre>
       *
       * <code>optional string diskless_stor_pool_uuid = 8;</code>
       */
      public Builder clearDisklessStorPoolUuid() {
        bitField0_ = (bitField0_ & ~0x00000080);
        disklessStorPoolUuid_ = getDefaultInstance().getDisklessStorPoolUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node's diskless stor pool uuid
       * </pre>
       *
       * <code>optional string diskless_stor_pool_uuid = 8;</code>
       */
      public Builder setDisklessStorPoolUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        disklessStorPoolUuid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.linbit.linstor.proto.Node)
    }

    // @@protoc_insertion_point(class_scope:com.linbit.linstor.proto.Node)
    private static final com.linbit.linstor.proto.NodeOuterClass.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linbit.linstor.proto.NodeOuterClass.Node();
    }

    public static com.linbit.linstor.proto.NodeOuterClass.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    public com.linbit.linstor.proto.NodeOuterClass.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_linstor_proto_Node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_linstor_proto_Node_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto/Node.proto\022\030com.linbit.linstor.p" +
      "roto\032\033proto/LinStorMapEntry.proto\032\030proto" +
      "/NetInterface.proto\"\355\001\n\004Node\022\014\n\004uuid\030\001 \001" +
      "(\t\022\014\n\004name\030\002 \002(\t\022\014\n\004type\030\003 \002(\t\0228\n\005props\030" +
      "\004 \003(\0132).com.linbit.linstor.proto.LinStor" +
      "MapEntry\022\r\n\005flags\030\005 \003(\t\022>\n\016net_interface" +
      "s\030\006 \003(\0132&.com.linbit.linstor.proto.NetIn" +
      "terface\022\021\n\tconnected\030\007 \001(\010\022\037\n\027diskless_s" +
      "tor_pool_uuid\030\010 \001(\tP\000P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.linbit.linstor.proto.LinStorMapEntryOuterClass.getDescriptor(),
          com.linbit.linstor.proto.NetInterfaceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_linbit_linstor_proto_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_linbit_linstor_proto_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_linstor_proto_Node_descriptor,
        new java.lang.String[] { "Uuid", "Name", "Type", "Props", "Flags", "NetInterfaces", "Connected", "DisklessStorPoolUuid", });
    com.linbit.linstor.proto.LinStorMapEntryOuterClass.getDescriptor();
    com.linbit.linstor.proto.NetInterfaceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
