// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linstor/proto/javainternal/MsgIntDelRsc.proto

package com.linbit.linstor.proto.javainternal;

public final class MsgIntDelRscOuterClass {
  private MsgIntDelRscOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgIntDelRscOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.linbit.linstor.proto.javainternal.MsgIntDelRsc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Resource description
     * </pre>
     *
     * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
     */
    boolean hasDeletedRsc();
    /**
     * <pre>
     * Resource description
     * </pre>
     *
     * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
     */
    com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc getDeletedRsc();
    /**
     * <pre>
     * Resource description
     * </pre>
     *
     * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
     */
    com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRscOrBuilder getDeletedRscOrBuilder();

    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    java.util.List<com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace> 
        getFreeSpaceList();
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace getFreeSpace(int index);
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    int getFreeSpaceCount();
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    java.util.List<? extends com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder> 
        getFreeSpaceOrBuilderList();
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder getFreeSpaceOrBuilder(
        int index);
  }
  /**
   * <pre>
   * linstor - Delete resource
   * </pre>
   *
   * Protobuf type {@code com.linbit.linstor.proto.javainternal.MsgIntDelRsc}
   */
  public  static final class MsgIntDelRsc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.linbit.linstor.proto.javainternal.MsgIntDelRsc)
      MsgIntDelRscOrBuilder {
    // Use MsgIntDelRsc.newBuilder() to construct.
    private MsgIntDelRsc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgIntDelRsc() {
      freeSpace_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MsgIntDelRsc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.Builder subBuilder = null;
              if (deletedRsc_ != null) {
                subBuilder = deletedRsc_.toBuilder();
              }
              deletedRsc_ = input.readMessage(com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deletedRsc_);
                deletedRsc_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                freeSpace_ = new java.util.ArrayList<com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace>();
                mutable_bitField0_ |= 0x00000002;
              }
              freeSpace_.add(
                  input.readMessage(com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          freeSpace_ = java.util.Collections.unmodifiableList(freeSpace_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc.class, com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc.Builder.class);
    }

    private int bitField0_;
    public static final int DELETED_RSC_FIELD_NUMBER = 1;
    private com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc deletedRsc_;
    /**
     * <pre>
     * Resource description
     * </pre>
     *
     * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
     */
    public boolean hasDeletedRsc() {
      return deletedRsc_ != null;
    }
    /**
     * <pre>
     * Resource description
     * </pre>
     *
     * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
     */
    public com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc getDeletedRsc() {
      return deletedRsc_ == null ? com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.getDefaultInstance() : deletedRsc_;
    }
    /**
     * <pre>
     * Resource description
     * </pre>
     *
     * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
     */
    public com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRscOrBuilder getDeletedRscOrBuilder() {
      return getDeletedRsc();
    }

    public static final int FREE_SPACE_FIELD_NUMBER = 2;
    private java.util.List<com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace> freeSpace_;
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    public java.util.List<com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace> getFreeSpaceList() {
      return freeSpace_;
    }
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    public java.util.List<? extends com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder> 
        getFreeSpaceOrBuilderList() {
      return freeSpace_;
    }
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    public int getFreeSpaceCount() {
      return freeSpace_.size();
    }
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    public com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace getFreeSpace(int index) {
      return freeSpace_.get(index);
    }
    /**
     * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
     */
    public com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder getFreeSpaceOrBuilder(
        int index) {
      return freeSpace_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasDeletedRsc()) {
        if (!getDeletedRsc().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getFreeSpaceCount(); i++) {
        if (!getFreeSpace(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deletedRsc_ != null) {
        output.writeMessage(1, getDeletedRsc());
      }
      for (int i = 0; i < freeSpace_.size(); i++) {
        output.writeMessage(2, freeSpace_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deletedRsc_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDeletedRsc());
      }
      for (int i = 0; i < freeSpace_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, freeSpace_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc)) {
        return super.equals(obj);
      }
      com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc other = (com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc) obj;

      boolean result = true;
      result = result && (hasDeletedRsc() == other.hasDeletedRsc());
      if (hasDeletedRsc()) {
        result = result && getDeletedRsc()
            .equals(other.getDeletedRsc());
      }
      result = result && getFreeSpaceList()
          .equals(other.getFreeSpaceList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDeletedRsc()) {
        hash = (37 * hash) + DELETED_RSC_FIELD_NUMBER;
        hash = (53 * hash) + getDeletedRsc().hashCode();
      }
      if (getFreeSpaceCount() > 0) {
        hash = (37 * hash) + FREE_SPACE_FIELD_NUMBER;
        hash = (53 * hash) + getFreeSpaceList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * linstor - Delete resource
     * </pre>
     *
     * Protobuf type {@code com.linbit.linstor.proto.javainternal.MsgIntDelRsc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.linbit.linstor.proto.javainternal.MsgIntDelRsc)
        com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRscOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc.class, com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc.Builder.class);
      }

      // Construct using com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFreeSpaceFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (deletedRscBuilder_ == null) {
          deletedRsc_ = null;
        } else {
          deletedRsc_ = null;
          deletedRscBuilder_ = null;
        }
        if (freeSpaceBuilder_ == null) {
          freeSpace_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          freeSpaceBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_descriptor;
      }

      public com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc getDefaultInstanceForType() {
        return com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc.getDefaultInstance();
      }

      public com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc build() {
        com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc buildPartial() {
        com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc result = new com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (deletedRscBuilder_ == null) {
          result.deletedRsc_ = deletedRsc_;
        } else {
          result.deletedRsc_ = deletedRscBuilder_.build();
        }
        if (freeSpaceBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            freeSpace_ = java.util.Collections.unmodifiableList(freeSpace_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.freeSpace_ = freeSpace_;
        } else {
          result.freeSpace_ = freeSpaceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc) {
          return mergeFrom((com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc other) {
        if (other == com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc.getDefaultInstance()) return this;
        if (other.hasDeletedRsc()) {
          mergeDeletedRsc(other.getDeletedRsc());
        }
        if (freeSpaceBuilder_ == null) {
          if (!other.freeSpace_.isEmpty()) {
            if (freeSpace_.isEmpty()) {
              freeSpace_ = other.freeSpace_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFreeSpaceIsMutable();
              freeSpace_.addAll(other.freeSpace_);
            }
            onChanged();
          }
        } else {
          if (!other.freeSpace_.isEmpty()) {
            if (freeSpaceBuilder_.isEmpty()) {
              freeSpaceBuilder_.dispose();
              freeSpaceBuilder_ = null;
              freeSpace_ = other.freeSpace_;
              bitField0_ = (bitField0_ & ~0x00000002);
              freeSpaceBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFreeSpaceFieldBuilder() : null;
            } else {
              freeSpaceBuilder_.addAllMessages(other.freeSpace_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasDeletedRsc()) {
          if (!getDeletedRsc().isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getFreeSpaceCount(); i++) {
          if (!getFreeSpace(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc deletedRsc_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc, com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.Builder, com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRscOrBuilder> deletedRscBuilder_;
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      public boolean hasDeletedRsc() {
        return deletedRscBuilder_ != null || deletedRsc_ != null;
      }
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      public com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc getDeletedRsc() {
        if (deletedRscBuilder_ == null) {
          return deletedRsc_ == null ? com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.getDefaultInstance() : deletedRsc_;
        } else {
          return deletedRscBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      public Builder setDeletedRsc(com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc value) {
        if (deletedRscBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deletedRsc_ = value;
          onChanged();
        } else {
          deletedRscBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      public Builder setDeletedRsc(
          com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.Builder builderForValue) {
        if (deletedRscBuilder_ == null) {
          deletedRsc_ = builderForValue.build();
          onChanged();
        } else {
          deletedRscBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      public Builder mergeDeletedRsc(com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc value) {
        if (deletedRscBuilder_ == null) {
          if (deletedRsc_ != null) {
            deletedRsc_ =
              com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.newBuilder(deletedRsc_).mergeFrom(value).buildPartial();
          } else {
            deletedRsc_ = value;
          }
          onChanged();
        } else {
          deletedRscBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      public Builder clearDeletedRsc() {
        if (deletedRscBuilder_ == null) {
          deletedRsc_ = null;
          onChanged();
        } else {
          deletedRsc_ = null;
          deletedRscBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      public com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.Builder getDeletedRscBuilder() {
        
        onChanged();
        return getDeletedRscFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      public com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRscOrBuilder getDeletedRscOrBuilder() {
        if (deletedRscBuilder_ != null) {
          return deletedRscBuilder_.getMessageOrBuilder();
        } else {
          return deletedRsc_ == null ?
              com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.getDefaultInstance() : deletedRsc_;
        }
      }
      /**
       * <pre>
       * Resource description
       * </pre>
       *
       * <code>.com.linbit.linstor.proto.MsgDelRsc deleted_rsc = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc, com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.Builder, com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRscOrBuilder> 
          getDeletedRscFieldBuilder() {
        if (deletedRscBuilder_ == null) {
          deletedRscBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc, com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRsc.Builder, com.linbit.linstor.proto.MsgDelRscOuterClass.MsgDelRscOrBuilder>(
                  getDeletedRsc(),
                  getParentForChildren(),
                  isClean());
          deletedRsc_ = null;
        }
        return deletedRscBuilder_;
      }

      private java.util.List<com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace> freeSpace_ =
        java.util.Collections.emptyList();
      private void ensureFreeSpaceIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          freeSpace_ = new java.util.ArrayList<com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace>(freeSpace_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder> freeSpaceBuilder_;

      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public java.util.List<com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace> getFreeSpaceList() {
        if (freeSpaceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(freeSpace_);
        } else {
          return freeSpaceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public int getFreeSpaceCount() {
        if (freeSpaceBuilder_ == null) {
          return freeSpace_.size();
        } else {
          return freeSpaceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace getFreeSpace(int index) {
        if (freeSpaceBuilder_ == null) {
          return freeSpace_.get(index);
        } else {
          return freeSpaceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder setFreeSpace(
          int index, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace value) {
        if (freeSpaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFreeSpaceIsMutable();
          freeSpace_.set(index, value);
          onChanged();
        } else {
          freeSpaceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder setFreeSpace(
          int index, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder builderForValue) {
        if (freeSpaceBuilder_ == null) {
          ensureFreeSpaceIsMutable();
          freeSpace_.set(index, builderForValue.build());
          onChanged();
        } else {
          freeSpaceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder addFreeSpace(com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace value) {
        if (freeSpaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFreeSpaceIsMutable();
          freeSpace_.add(value);
          onChanged();
        } else {
          freeSpaceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder addFreeSpace(
          int index, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace value) {
        if (freeSpaceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFreeSpaceIsMutable();
          freeSpace_.add(index, value);
          onChanged();
        } else {
          freeSpaceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder addFreeSpace(
          com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder builderForValue) {
        if (freeSpaceBuilder_ == null) {
          ensureFreeSpaceIsMutable();
          freeSpace_.add(builderForValue.build());
          onChanged();
        } else {
          freeSpaceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder addFreeSpace(
          int index, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder builderForValue) {
        if (freeSpaceBuilder_ == null) {
          ensureFreeSpaceIsMutable();
          freeSpace_.add(index, builderForValue.build());
          onChanged();
        } else {
          freeSpaceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder addAllFreeSpace(
          java.lang.Iterable<? extends com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace> values) {
        if (freeSpaceBuilder_ == null) {
          ensureFreeSpaceIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, freeSpace_);
          onChanged();
        } else {
          freeSpaceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder clearFreeSpace() {
        if (freeSpaceBuilder_ == null) {
          freeSpace_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          freeSpaceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public Builder removeFreeSpace(int index) {
        if (freeSpaceBuilder_ == null) {
          ensureFreeSpaceIsMutable();
          freeSpace_.remove(index);
          onChanged();
        } else {
          freeSpaceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder getFreeSpaceBuilder(
          int index) {
        return getFreeSpaceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder getFreeSpaceOrBuilder(
          int index) {
        if (freeSpaceBuilder_ == null) {
          return freeSpace_.get(index);  } else {
          return freeSpaceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public java.util.List<? extends com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder> 
           getFreeSpaceOrBuilderList() {
        if (freeSpaceBuilder_ != null) {
          return freeSpaceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(freeSpace_);
        }
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder addFreeSpaceBuilder() {
        return getFreeSpaceFieldBuilder().addBuilder(
            com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.getDefaultInstance());
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder addFreeSpaceBuilder(
          int index) {
        return getFreeSpaceFieldBuilder().addBuilder(
            index, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.getDefaultInstance());
      }
      /**
       * <code>repeated .com.linbit.linstor.proto.StorPoolFreeSpace free_space = 2;</code>
       */
      public java.util.List<com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder> 
           getFreeSpaceBuilderList() {
        return getFreeSpaceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder> 
          getFreeSpaceFieldBuilder() {
        if (freeSpaceBuilder_ == null) {
          freeSpaceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpace.Builder, com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.StorPoolFreeSpaceOrBuilder>(
                  freeSpace_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          freeSpace_ = null;
        }
        return freeSpaceBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.linbit.linstor.proto.javainternal.MsgIntDelRsc)
    }

    // @@protoc_insertion_point(class_scope:com.linbit.linstor.proto.javainternal.MsgIntDelRsc)
    private static final com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc();
    }

    public static com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgIntDelRsc>
        PARSER = new com.google.protobuf.AbstractParser<MsgIntDelRsc>() {
      public MsgIntDelRsc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgIntDelRsc(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgIntDelRsc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgIntDelRsc> getParserForType() {
      return PARSER;
    }

    public com.linbit.linstor.proto.javainternal.MsgIntDelRscOuterClass.MsgIntDelRsc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-linstor/proto/javainternal/MsgIntDelRs" +
      "c.proto\022%com.linbit.linstor.proto.javain" +
      "ternal\032\035linstor/proto/MsgDelRsc.proto\032%l" +
      "instor/proto/StorPoolFreeSpace.proto\"\211\001\n" +
      "\014MsgIntDelRsc\0228\n\013deleted_rsc\030\001 \001(\0132#.com" +
      ".linbit.linstor.proto.MsgDelRsc\022?\n\nfree_" +
      "space\030\002 \003(\0132+.com.linbit.linstor.proto.S" +
      "torPoolFreeSpaceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.linbit.linstor.proto.MsgDelRscOuterClass.getDescriptor(),
          com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_linstor_proto_javainternal_MsgIntDelRsc_descriptor,
        new java.lang.String[] { "DeletedRsc", "FreeSpace", });
    com.linbit.linstor.proto.MsgDelRscOuterClass.getDescriptor();
    com.linbit.linstor.proto.StorPoolFreeSpaceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
