package com.linbit.linstor.layer.drbd.resfiles;

import com.linbit.ImplementationError;
import com.linbit.InvalidNameException;
import com.linbit.drbd.DrbdVersion;
import com.linbit.linstor.InternalApiConsts;
import com.linbit.linstor.LinStorException;
import com.linbit.linstor.LinStorRuntimeException;
import com.linbit.linstor.PriorityProps;
import com.linbit.linstor.PriorityProps.MultiResult;
import com.linbit.linstor.PriorityProps.ValueWithDescription;
import com.linbit.linstor.annotation.Nullable;
import com.linbit.linstor.api.ApiConsts;
import com.linbit.linstor.api.prop.LinStorObject;
import com.linbit.linstor.api.prop.WhitelistProps;
import com.linbit.linstor.core.LinStor;
import com.linbit.linstor.core.identifier.NetInterfaceName;
import com.linbit.linstor.core.identifier.VolumeNumber;
import com.linbit.linstor.core.objects.NetInterface;
import com.linbit.linstor.core.objects.Node;
import com.linbit.linstor.core.objects.NodeConnection;
import com.linbit.linstor.core.objects.Resource;
import com.linbit.linstor.core.objects.ResourceConnection;
import com.linbit.linstor.core.objects.ResourceDefinition;
import com.linbit.linstor.core.objects.ResourceGroup;
import com.linbit.linstor.core.objects.StorPool;
import com.linbit.linstor.core.objects.Volume;
import com.linbit.linstor.core.objects.VolumeDefinition;
import com.linbit.linstor.core.types.LsIpAddress;
import com.linbit.linstor.core.types.TcpPortNumber;
import com.linbit.linstor.layer.drbd.DrbdLayer;
import com.linbit.linstor.layer.drbd.resfiles.ConfFileBuilderAutoRules.AutoRule;
import com.linbit.linstor.logging.ErrorReporter;
import com.linbit.linstor.propscon.InvalidKeyException;
import com.linbit.linstor.propscon.ReadOnlyProps;
import com.linbit.linstor.storage.StorageException;
import com.linbit.linstor.storage.data.adapter.drbd.DrbdRscData;
import com.linbit.linstor.storage.data.adapter.drbd.DrbdRscDfnData;
import com.linbit.linstor.storage.data.adapter.drbd.DrbdVlmData;
import com.linbit.linstor.storage.interfaces.categories.resource.AbsRscLayerObject;
import com.linbit.linstor.storage.interfaces.categories.resource.VlmProviderObject;
import com.linbit.linstor.storage.interfaces.layers.drbd.DrbdRscObject.DrbdRscFlags;
import com.linbit.linstor.storage.kinds.DeviceLayerKind;
import com.linbit.linstor.storage.kinds.ExtToolsInfo;
import com.linbit.linstor.storage.utils.LayerUtils;
import com.linbit.utils.PairNonNull;
import com.linbit.utils.StringUtils;
import com.linbit.utils.TimeUtils;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Comparator;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

import org.slf4j.event.Level;

public class ConfFileBuilder
{
    private static final ResourceNameComparator RESOURCE_NAME_COMPARATOR = new ResourceNameComparator();
    public static final ExtToolsInfo.Version VERSION_9_34_0 = new ExtToolsInfo.Version(9, 34, 0);
    public static final ExtToolsInfo.Version VERSION_9_23_1 = new ExtToolsInfo.Version(9, 23, 1);

    /** Placeholder disk path for diskful peer volumes; explained by a comment in the generated file */
    public static final String PEER_DISK_PLACEHOLDER = "/dev/drbd/this/is/not/used";

    private final ErrorReporter errorReporter;
    private final DrbdRscData<Resource> localRscData;
    private final Collection<DrbdRscData<Resource>> remoteResourceData;
    private final WhitelistProps whitelistProps;
    private final ReadOnlyProps stltProps;
    private final DrbdVersion drbdVersion;

    private final StringBuilder stringBuilder;
    private int indentDepth;

    public ConfFileBuilder(
        final ErrorReporter errorReporterRef,
        final DrbdRscData<Resource> localRscRef,
        final Collection<DrbdRscData<Resource>> remoteResourcesRef,
        final WhitelistProps whitelistPropsRef,
        final ReadOnlyProps stltPropsRef,
        final DrbdVersion drbdVersionRef
    )
    {
        errorReporter = errorReporterRef;
        localRscData = localRscRef;
        remoteResourceData = remoteResourcesRef;
        whitelistProps = whitelistPropsRef;
        stltProps = stltPropsRef;
        drbdVersion = drbdVersionRef;

        stringBuilder = new StringBuilder();
        indentDepth = 0;
    }

    private String header() throws InvalidKeyException
    {
        StringBuilder sb = new StringBuilder();
        sb.append(
            String.format(
                "# This file was generated by LINSTOR (%s), do not edit manually.",
                LinStor.VERSION_INFO_PROVIDER.getVersion()
            )
        );

        sb.append("\n# Name\n#   LINSTOR nodename: ")
            .append(localRscData.getAbsResource().getNode().getName().displayValue)
            .append("\n#   Local hostname  : ")
            .append(localRscData.getAbsResource().getNode().getProps().getProp(InternalApiConsts.NODE_UNAME));

        sb.append("\n# File generated at: \n#   Local time      : ")
            .append(TimeUtils.JOURNALCTL_DF.format(LocalDateTime.now(ZoneId.systemDefault())))
            .append("\n#   UTC             : ")
            .append(TimeUtils.JOURNALCTL_DF.format(LocalDateTime.now(ZoneOffset.UTC)));

        return sb.toString();
    }

    public String build()
        throws StorageException
    {
        Set<DrbdRscData<Resource>> peerRscSet = new TreeSet<>(RESOURCE_NAME_COMPARATOR);
        DrbdRscDfnData<Resource> rscDfnData = localRscData.getRscDfnLayerObject();
        peerRscSet.addAll(remoteResourceData); // node-alphabetically sorted

        Resource localRsc = localRscData.getAbsResource();
        final ResourceDefinition rscDfn = localRsc.getResourceDefinition();
        if (rscDfn == null)
        {
            throw new ImplementationError("No resource definition found for " + localRsc + "!");
        }
        final ReadOnlyProps localRscProps = localRsc.getProps();
        final ReadOnlyProps rscDfnProps = rscDfn.getProps();
        final ResourceGroup rscGrp = rscDfn.getResourceGroup();
        final ReadOnlyProps rscGrpProps = rscGrp.getProps();
        final Node localNode = localRscData.getAbsResource().getNode();
        final String localNodeName = localNode.getName().displayValue;

        appendLine(header());
        appendLine("");
        appendLine("resource \"%s\"", localRscData.getSuffixedResourceName());
        try (Section resourceSection = new Section())
        {
            PriorityProps localRscPrioProps = new PriorityProps()
                .addProps(localRscProps, "R (" + rscDfn.getName() + ")")
                .addProps(rscDfnProps, "RD (" + rscDfn.getName() + ")")
                .addProps(rscGrpProps, "RG (" + rscGrp.getName() + ")")
                .addProps(localRsc.getNode().getProps(), "N (" + localNodeName + ")")
                .addProps(stltProps, "C");

            // set auto verify algorithm if none is set yet by the user
            final String verifyAlgo = localRscPrioProps.getProp(
                InternalApiConsts.DRBD_VERIFY_ALGO, ApiConsts.NAMESPC_DRBD_NET_OPTIONS);
            final String autoVerifyAlgo = localRscPrioProps.getProp(
                InternalApiConsts.DRBD_AUTO_VERIFY_ALGO, ApiConsts.NAMESPC_DRBD_OPTIONS);

            final PriorityProps prioProps = new PriorityProps(
                rscDfnProps,
                rscGrpProps,
                stltProps
            );
            final String disableAutoVerifyAlgo = prioProps.getProp(ApiConsts.KEY_DRBD_DISABLE_AUTO_VERIFY_ALGO,
                ApiConsts.NAMESPC_DRBD_OPTIONS);

            if (StringUtils.propFalseOrNull(disableAutoVerifyAlgo) && verifyAlgo == null && autoVerifyAlgo != null)
            {
                localRscPrioProps.setFallbackProp(
                    InternalApiConsts.DRBD_VERIFY_ALGO,
                    autoVerifyAlgo,
                    ApiConsts.NAMESPC_DRBD_NET_OPTIONS);
            }

            final ConfFileBuilderAutoRules localRscAutoRules = new ConfFileBuilderAutoRules(localRscData);
            if (localRscPrioProps.anyPropsHasNamespace(ApiConsts.NAMESPC_DRBD_HANDLER_OPTIONS))
            {
                appendLine("");
                appendLine("handlers");
                try (Section optionsSection = new Section())
                {
                    appendConflictingDrbdOptions(
                        LinStorObject.CTRL,
                        ApiConsts.NAMESPC_DRBD_HANDLER_OPTIONS,
                        localRscPrioProps,
                        localRscAutoRules,
                        false
                    );
                }
            }

            if (localRscPrioProps.anyPropsHasNamespace(ApiConsts.NAMESPC_DRBD_RESOURCE_OPTIONS))
            {
                appendLine("");
                appendLine("options");
                try (Section optionsSection = new Section())
                {
                    appendConflictingDrbdOptions(
                        LinStorObject.CTRL,
                        ApiConsts.NAMESPC_DRBD_RESOURCE_OPTIONS,
                        localRscPrioProps,
                        localRscAutoRules,
                        false
                    );
                }
            }

            appendLine("");
            appendLine("net");
            try (Section netSection = new Section())
            {
                // TODO: make configurable
                appendLine("cram-hmac-alg     sha1;");
                // TODO: make configurable
                appendLine("shared-secret     \"%s\";", rscDfnData.getSecret());

                appendConflictingDrbdOptions(
                    LinStorObject.CTRL,
                    ApiConsts.NAMESPC_DRBD_NET_OPTIONS,
                    localRscPrioProps,
                    localRscAutoRules,
                    false
                );
            }

            if (localRscPrioProps.anyPropsHasNamespace(ApiConsts.NAMESPC_DRBD_DISK_OPTIONS))
            {
                appendLine("");
                appendLine("disk");
                try (Section ignore = new Section())
                {
                    appendConflictingDrbdOptions(
                        LinStorObject.CTRL,
                        ApiConsts.NAMESPC_DRBD_DISK_OPTIONS,
                        localRscPrioProps,
                        localRscAutoRules,
                        false
                    );
                }
            }

            // currently we only consider one port...
            final int localPort = localRscData.getTcpPortList().iterator().next().value;

            // Create local network configuration
            {
                appendLine("");
                appendLine("on \"%s\"", localRsc.getNode().getProps().getPropWithDefault(
                    InternalApiConsts.NODE_UNAME,
                    localRsc.getNode().getName().displayValue)
                );
                try (Section onSection = new Section())
                {
                    Collection<DrbdVlmData<Resource>> vlmDataList = localRscData.getVlmLayerObjects().values();
                    for (DrbdVlmData<Resource> vlmData : vlmDataList)
                    {
                        appendVlmIfPresent(vlmData, false);
                    }
                    appendLine("node-id    %d;", localRscData.getNodeId().value);
                }
            }

            for (final DrbdRscData<Resource> peerRscData : peerRscSet)
            {
                Resource peerRsc = peerRscData.getAbsResource();
                if (peerRsc.getStateFlags().isUnset(Resource.Flags.DELETE))
                {
                    appendLine("");
                    appendLine("on \"%s\"", peerRsc.getNode().getProps()
                        .getPropWithDefault(
                            InternalApiConsts.NODE_UNAME,
                            peerRsc.getNode().getName().displayValue)
                    );
                    try (Section onSection = new Section())
                    {
                        Collection<DrbdVlmData<Resource>> peerVlmDataList = peerRscData
                            .getVlmLayerObjects().values();
                        for (DrbdVlmData<Resource> peerVlmData : peerVlmDataList)
                        {
                            appendVlmIfPresent(peerVlmData, true);
                        }

                        appendLine("node-id    %d;", peerRscData.getNodeId().value);

                        // TODO: implement "multi-connection / path magic" (nodeMeshes + singleConnections vars)
                        // sb.append(peerResource.co)
                    }
                }
            }

            // first generate all with local first
            for (final DrbdRscData<Resource> peerRscData : peerRscSet)
            {
                // currently we only consider one port...
                final int peerPort = peerRscData.getTcpPortList().iterator().next().value;

                final ConfFileBuilderAutoRules peerRscAutoRules = new ConfFileBuilderAutoRules(peerRscData);

                Resource peerRsc = peerRscData.getAbsResource();
                // don't create a connection entry if the resource has the deleted flag
                // or if it is a connection between two diskless nodes
                if (
                    peerRsc.getStateFlags().isUnset(Resource.Flags.DELETE) &&
                        !(peerRsc.disklessForDrbdPeers() &&
                            localRsc.getStateFlags().isSet(Resource.Flags.DRBD_DISKLESS))
                )
                {
                    appendLine("");
                    appendLine("connection");
                    try (Section connectionSection = new Section())
                    {
                        NodeConnection nodeConn = localRsc.getNode().getNodeConnection(peerRsc.getNode());
                        @Nullable ResourceConnection rscConn = localRsc.getAbsResourceConnection(peerRsc);
                        @Nullable ReadOnlyProps paths = getPathsNamespace(localRsc, peerRsc);

                        PriorityProps prioPropsConn = new PriorityProps();
                        if (rscConn != null)
                        {
                            prioPropsConn.addProps(
                                rscConn.getProps(),
                                String.format(
                                    "Resource connection(%s <-> %s)",
                                    rscConn.getSourceResource(),
                                    rscConn.getTargetResource()
                                )
                            );
                        }
                        prioPropsConn.addProps(rscDfnProps, "RD (" + rscDfn.getName() + ")");

                        if (nodeConn != null)
                        {
                            prioPropsConn = prioPropsConn.addProps(
                                nodeConn.getProps(),
                                String.format(
                                    "Node connection(%s <-> %s)",
                                    nodeConn.getSourceNode(),
                                    nodeConn.getTargetNode()
                                )
                            );
                        }

                        prioPropsConn.addProps(rscGrpProps, "RG (" + rscGrp.getName() + ")");
                        prioPropsConn.addProps(stltProps, "C");

                        if (prioPropsConn.anyPropsHasNamespace(ApiConsts.NAMESPC_DRBD_NET_OPTIONS))
                        {
                            appendLine("");
                            appendLine("net");
                            try (Section ignore = new Section())
                            {
                                appendConflictingDrbdOptions(
                                    LinStorObject.CTRL,
                                    ApiConsts.NAMESPC_DRBD_NET_OPTIONS,
                                    prioPropsConn,
                                    peerRscAutoRules,
                                    true
                                );
                            }
                        }

                        if (prioPropsConn.anyPropsHasNamespace(ApiConsts.NAMESPC_DRBD_PEER_DEVICE_OPTIONS))
                        {
                            appendLine("");
                            appendLine("disk");
                            try (Section ignore = new Section())
                            {
                                appendConflictingDrbdOptions(
                                    LinStorObject.CTRL,
                                    ApiConsts.NAMESPC_DRBD_PEER_DEVICE_OPTIONS,
                                    prioPropsConn,
                                    peerRscAutoRules,
                                    true
                                );
                            }
                        }

                        if (paths != null)
                        {
                            List<PairNonNull<NetInterface, NetInterface>> pathsList = parseConnectionPaths(
                                paths,
                                localRsc,
                                peerRsc
                            );

                            // add network connection paths...
                            for (PairNonNull<NetInterface, NetInterface> path : pathsList)
                            {
                                if (!path.equals(pathsList.get(0)))
                                {
                                    appendLine("");
                                }
                                appendLine("path");
                                try (Section pathSection = new Section())
                                {
                                    int portA;
                                    int portB;
                                    NetInterface netIfA;
                                    NetInterface netIfB;
                                    if (path.objA.getNode().equals(localNode))
                                    {
                                        portA = localPort;
                                        portB = peerPort;
                                        netIfA = getOutsideNetIf(localRscData);
                                        netIfB = getOutsideNetIf(peerRscData);
                                    }
                                    else
                                    {
                                        portA = peerPort;
                                        portB = localPort;
                                        netIfA = getOutsideNetIf(peerRscData);
                                        netIfB = getOutsideNetIf(localRscData);
                                    }

                                    appendConnectionHost(
                                        portA,
                                        rscConn,
                                        path.objA,
                                        netIfA
                                    );
                                    appendConnectionHost(
                                        portB,
                                        rscConn,
                                        path.objB,
                                        netIfB
                                    );
                                }
                            }
                        }
                        else
                        {
                            // ...or fall back to previous implementation
                            appendConnectionHost(
                                localPort,
                                rscConn,
                                getPreferredNetIf(localRscData, stltProps, errorReporter),
                                getOutsideNetIf(localRscData)
                            );
                            appendConnectionHost(
                                peerPort,
                                rscConn,
                                getPreferredNetIf(peerRscData, stltProps, errorReporter),
                                getOutsideNetIf(peerRscData)
                            );
                        }
                    }
                }
            }

            String compressionTypeProp = localRscPrioProps.getProp(
                ApiConsts.KEY_DRBD_PROXY_COMPRESSION_TYPE,
                ApiConsts.NAMESPC_DRBD_PROXY
            );

            if (localRscPrioProps.anyPropsHasNamespace(ApiConsts.NAMESPC_DRBD_PROXY_OPTIONS) ||
                compressionTypeProp != null)
            {
                appendLine("");
                appendLine("proxy");
                try (Section ignore = new Section())
                {
                    appendConflictingDrbdOptions(
                        LinStorObject.DRBD_PROXY,
                        ApiConsts.NAMESPC_DRBD_PROXY_OPTIONS,
                        localRscPrioProps,
                        localRscAutoRules,
                        false
                    );

                    if (compressionTypeProp != null)
                    {
                        appendCompressionPlugin(rscDfn, compressionTypeProp);
                    }
                }
            }
        }

        return stringBuilder.toString();
    }

    private void appendConnectionHost(
        int portRef,
        @Nullable ResourceConnection rscConn,
        NetInterface netIf,
        @Nullable NetInterface outsideNetIf
    )
    {
        TcpPortNumber rscConnPort = rscConn == null ? null : rscConn.getDrbdProxyPortSource();
        int port = rscConnPort == null ? portRef : rscConnPort.value;

        String localAddress = formatAddress(netIf, port);

        String hostName = netIf.getNode().getProps().getPropWithDefault(
            InternalApiConsts.NODE_UNAME,
            netIf.getNode().getName().displayValue
        );

        if (rscConn != null && rscConn.getStateFlags().isSet(ResourceConnection.Flags.LOCAL_DRBD_PROXY))
        {
            appendLine("host \"%s\" address 127.0.0.1:%d via proxy on %s", hostName, port, hostName);
            try (Section ignore = new Section())
            {
                appendLine("inside 127.0.0.2:%d;", port);
                appendLine("outside %s;", localAddress);
            }
        }
        else if (outsideNetIf != null)
        {
            appendLine(
                "host \"%s\" address %s via outside-address %s;",
                hostName,
                localAddress,
                formatAddress(outsideNetIf, port)
            );
        }
        else
        {
            appendLine("host \"%s\" address %s;", hostName, localAddress);
        }
    }

    private String formatAddress(NetInterface netIfRef, int port)
    {
        String ret;
        LsIpAddress addr = netIfRef.getAddress();
        String addrText = addr.getAddress();

        if (addr.getAddressType() == LsIpAddress.AddrType.IPv6)
        {
            ret = String.format("ipv6 [%s]:%d", addrText, port);
        }
        else
        {
            ret = String.format("ipv4 %s:%d", addrText, port);
        }

        return ret;
    }

    private void appendCompressionPlugin(ResourceDefinition rscDfn, String compressionType)
    {
        appendLine("plugin");
        try (Section pluginSection = new Section())
        {
            String namespace = ApiConsts.NAMESPC_DRBD_PROXY_COMPRESSION_OPTIONS;

            List<String> compressionPluginTerms = new ArrayList<>();
            compressionPluginTerms.add(compressionType);

            Map<String, String> drbdProps = new PriorityProps(
                rscDfn.getProps(),
                rscDfn.getResourceGroup().getProps(),
                stltProps
            )
                .renderRelativeMap(namespace);

            for (Map.Entry<String, String> entry : drbdProps.entrySet())
            {
                String key = entry.getKey();
                String value = entry.getValue();
                if (checkValidDrbdOption(LinStorObject.drbdProxyCompressionObject(compressionType), key, value))
                {
                    compressionPluginTerms.add(key.substring(namespace.length() + 1));
                    compressionPluginTerms.add(value);
                }
            }

            appendLine("%s;", String.join(" ", compressionPluginTerms));
        }
    }

    private boolean checkValidDrbdOption(
        final LinStorObject lsObj,
        final String key,
        final String value
    )
    {
        boolean ret = true;
        if (!whitelistProps.isAllowed(lsObj, new ArrayList<>(), key, value, true))
        {
            ret = false;
            errorReporter.reportProblem(
                Level.WARN,
                new LinStorException(
                    "Ignoring property '" + key + "' with value '" + value + "' as it is not a valid property key."
                ),
                null,
                "The whitelist was generated from 'drbdsetup xml-help {resource,peer-device,net,disk}-options'" +
                    " when the satellite started."
            );
        }

        return ret;
    }

    @SuppressWarnings({"checkstyle:IllegalToken", "checkstyle:MagicNumber"})
    private void appendConflictingDrbdOptions(
        final LinStorObject lsObj,
        final String namespace,
        final PriorityProps prioProps,
        final ConfFileBuilderAutoRules autoRules,
        final boolean isPeerRsc
    )
    {
        Map<String, MultiResult> map = prioProps.renderConflictingMap(namespace, true);
        int substrFrom = namespace.length() + 1;

        StringBuilder confLine = new StringBuilder();
        ExtToolsInfo.Version drbdUtilsVersion = drbdVersion.getUtilsVsn();
        for (Entry<String, MultiResult> entry : map.entrySet())
        {
            if (isPeerRsc && entry.getKey().endsWith("resync-after") &&
                !drbdUtilsVersion.greaterOrEqual(VERSION_9_23_1))
            {
                continue;
            }

            if (entry.getKey().endsWith("/discard-granularity") &&
                !drbdUtilsVersion.greaterOrEqual(VERSION_9_34_0))
            {
                continue;
            }

            confLine.setLength(0);

            appendIndent(confLine);

            String keyWithNamespace = entry.getKey();
            String keyWithoutNamespace = keyWithNamespace.substring(substrFrom);

            MultiResult multiResult = entry.getValue();
            String value = null;

            boolean isAutoEnabled = false;
            AutoRule autoRule = autoRules.get(keyWithNamespace);

            if (autoRule != null)
            {
                /*
                 * We need to check whether the automation is enabled.
                 * If it is enabled, it means that the controller is managing this property only on the Props of the
                 * Pair, not on any other level.
                 * We therefore must ignore the entries in the priorityProps and only check for the entry in the given
                 * Props. That also means that we deliberately need to allow null values, even if other entries of the
                 * PrioProps would say otherwise.
                 *
                 * If the automation is disabled, we continue with the MultiResult.
                 */
                String keyEnabledAuto = autoRule.key;
                String valEnabledAuto = prioProps.getProp(keyEnabledAuto);
                if (valEnabledAuto == null || valEnabledAuto.equalsIgnoreCase(ApiConsts.VAL_TRUE))
                {
                    value = autoRule.props.getProp(keyWithNamespace);
                    isAutoEnabled = true;
                }
            }

            if (!isAutoEnabled)
            {
                value = multiResult.first.value;
            }

            /*
             * We do not want "null" values to be in the config file, but since the autoRule
             * is active instead of falling back to the prioProp-value, we simply ignore this entry
             */
            if ((value != null || !isAutoEnabled) && checkValidDrbdOption(lsObj, keyWithNamespace, value))
            {
                final boolean quoteValue = whitelistProps.needsQuoting(lsObj, keyWithNamespace);
                confLine.append(
                    String.format(
                        quoteValue ? "%s \"%s\";" : "%s %s;",
                        keyWithoutNamespace,
                        value
                    )
                );
                append(confLine.toString());

                if (!isAutoEnabled && !multiResult.conflictingList.isEmpty())
                {
                    int commentPos = confLine.length() + 1;
                    confLine.setLength(0);

                    char[] spacesChar = new char[commentPos];
                    Arrays.fill(spacesChar, ' ');
                    String spaces = new String(spacesChar);

                    for (ValueWithDescription valueWithDescription : multiResult.conflictingList)
                    {
                        append(
                            "%s# overrides value '%s' from %s%n",
                            spaces,
                            valueWithDescription.value,
                            valueWithDescription.propsDescription
                        );
                    }
                }
                else
                {
                    append("%n");
                }
            }
        }
    }

    /**
     * Returns the namespace containing the configured connection paths between the two given resources, taken from
     * the resource connection or, if the resource connection has no paths configured, from the node connection.
     * Returns {@code null} if neither has configured paths.
     */
    public static @Nullable ReadOnlyProps getPathsNamespace(Resource localRsc, Resource peerRsc)
    {
        @Nullable ReadOnlyProps paths = null;
        @Nullable ResourceConnection rscConn = localRsc.getAbsResourceConnection(peerRsc);
        if (rscConn != null)
        {
            // get paths from resource connection...
            paths = rscConn.getProps().getNamespace(ApiConsts.NAMESPC_CONNECTION_PATHS);
        }
        if (paths == null)
        {
            // ...or fall back to node connection
            NodeConnection nodeConn = localRsc.getNode().getNodeConnection(peerRsc.getNode());
            if (nodeConn != null)
            {
                paths = nodeConn.getProps().getNamespace(ApiConsts.NAMESPC_CONNECTION_PATHS);
            }
        }
        return paths;
    }

    /**
     * Parses the given connection paths namespace (see {@link #getPathsNamespace(Resource, Resource)}) into pairs of
     * {@link NetInterface}s. The order within a pair is not defined, i.e. either side of a pair might belong to the
     * local node.
     */
    public static List<PairNonNull<NetInterface, NetInterface>> parseConnectionPaths(
        ReadOnlyProps pathsRef,
        Resource localRsc,
        Resource peerRsc
    )
        throws StorageException
    {
        List<PairNonNull<NetInterface, NetInterface>> pathsList = new ArrayList<>();

        // iterate through network connection paths
        Iterator<String> pathsIterator = pathsRef.iterateNamespaces();
        while (pathsIterator.hasNext())
        {
            String path = pathsIterator.next();
            ReadOnlyProps ncEntryNamespace = pathsRef.getNamespace(path);

            if (ncEntryNamespace != null && ncEntryNamespace.map().size() == 2)
            {
                Node firstNode = peerRsc.getNode();
                Node secondNode = localRsc.getNode();
                try
                {
                    // iterate through nodes (should be exactly 2)
                    Iterator<String> nodesIterator = ncEntryNamespace.keysIterator();
                    String firstNodeName = StringUtils.split(nodesIterator.next(), "/")[2];
                    String secondNodeName = StringUtils.split(nodesIterator.next(), "/")[2];

                    // keep order of nodes correct
                    if (firstNode.getName().value.equalsIgnoreCase(secondNodeName) &&
                        secondNode.getName().value.equalsIgnoreCase(firstNodeName))
                    {
                        Node temp = firstNode;
                        firstNode = secondNode;
                        secondNode = temp;
                    }
                    else
                    if (!(firstNode.getName().value.equalsIgnoreCase(firstNodeName) &&
                            secondNode.getName().value.equalsIgnoreCase(secondNodeName)))
                    {
                        throw new ImplementationError(
                            "Configured node names " + firstNodeName + " and " +
                            secondNodeName + " do not match the actual node names."
                        );
                    }

                    // get corresponding network interfaces
                    String nicName = ncEntryNamespace.getProp(firstNodeName);
                    NetInterface firstNic = firstNode.getNetInterface(new NetInterfaceName(nicName));

                    if (firstNic == null)
                    {
                        throw new StorageException("Network interface '" + nicName +
                            "' of node '" + firstNode + "' does not exist!");
                    }

                    nicName = ncEntryNamespace.getProp(secondNodeName);
                    NetInterface secondNic = secondNode.getNetInterface(new NetInterfaceName(nicName));

                    if (secondNic == null)
                    {
                        throw new StorageException("Network interface '" + nicName +
                            "' of node '" + secondNode + "' does not exist!");
                    }

                    pathsList.add(new PairNonNull<>(firstNic, secondNic));
                }
                catch (InvalidKeyException exc)
                {
                    throw new ImplementationError(
                        "No network interface configured!", exc);
                }
                catch (InvalidNameException exc)
                {
                    throw new StorageException(
                        "Name format of for network interface is not valid!", exc);
                }
            }
            else
            {
                throw new ImplementationError(
                    "When configuring a path it must contain exactly two nodes!");
            }
        }

        return pathsList;
    }

    /**
     * Returns the set of local IP addresses the local DRBD resource will bind its listeners to, using the same
     * NetInterface resolution as the res file generation: configured connection paths per peer, with the
     * PrefNic based lookup as fallback. For connections using a local DRBD proxy, DRBD itself binds to loopback
     * addresses instead.
     */
    public static Set<InetAddress> getLocalBindAddresses(
        DrbdRscData<Resource> localRscDataRef,
        Collection<DrbdRscData<Resource>> peerRscDataListRef,
        ReadOnlyProps stltPropsRef,
        ErrorReporter errorReporterRef
    )
        throws StorageException
    {
        Set<InetAddress> bindAddrs = new LinkedHashSet<>();
        Resource localRsc = localRscDataRef.getAbsResource();
        Node localNode = localRsc.getNode();

        boolean usePreferredNetIf = false;
        for (DrbdRscData<Resource> peerRscData : peerRscDataListRef)
        {
            Resource peerRsc = peerRscData.getAbsResource();
            // same conditions as the res file generation uses for creating connection sections
            if (
                peerRsc.getStateFlags().isUnset(Resource.Flags.DELETE) &&
                    !(peerRsc.disklessForDrbdPeers() &&
                        localRsc.getStateFlags().isSet(Resource.Flags.DRBD_DISKLESS))
            )
            {
                @Nullable ResourceConnection rscConn = localRsc.getAbsResourceConnection(peerRsc);
                if (rscConn != null && rscConn.getStateFlags().isSet(ResourceConnection.Flags.LOCAL_DRBD_PROXY))
                {
                    // DRBD itself binds to 127.0.0.1, the proxy binds 127.0.0.2 (inside) as well as the
                    // NetIf resolved below (outside), all on the same port
                    addIpAddress(bindAddrs, "127.0.0.1", errorReporterRef);
                    addIpAddress(bindAddrs, "127.0.0.2", errorReporterRef);
                }
                @Nullable ReadOnlyProps paths = getPathsNamespace(localRsc, peerRsc);
                if (paths != null)
                {
                    for (PairNonNull<NetInterface, NetInterface> path : parseConnectionPaths(paths, localRsc, peerRsc))
                    {
                        NetInterface localNetIf = path.objA.getNode().equals(localNode) ? path.objA : path.objB;
                        addIpAddress(bindAddrs, localNetIf.getAddress().getAddress(), errorReporterRef);
                    }
                }
                else
                {
                    usePreferredNetIf = true;
                }
            }
        }
        if (usePreferredNetIf || bindAddrs.isEmpty())
        {
            @Nullable NetInterface preferredNetIf = getPreferredNetIf(localRscDataRef, stltPropsRef, errorReporterRef);
            if (preferredNetIf != null)
            {
                addIpAddress(bindAddrs, preferredNetIf.getAddress().getAddress(), errorReporterRef);
            }
        }
        return bindAddrs;
    }

    private static void addIpAddress(Set<InetAddress> bindAddrsRef, String ipAddrRef, ErrorReporter errorReporterRef)
    {
        try
        {
            bindAddrsRef.add(InetAddress.getByName(ipAddrRef));
        }
        catch (UnknownHostException exc)
        {
            // cannot happen with a valid IP literal, but just in case
            errorReporterRef.logWarning("Failed to parse IP address '%s', skipping", ipAddrRef);
        }
    }

    private static @Nullable NetInterface getPreferredNetIf(
        DrbdRscData<Resource> peerRscDataRef,
        ReadOnlyProps stltPropsRef,
        ErrorReporter errorReporterRef
    )
    {
        @Nullable NetInterface preferredNetIf = null;
        try
        {
            PriorityProps prioProps = new PriorityProps();

            Resource rsc = peerRscDataRef.getAbsResource();
            Node node = rsc.getNode();

            Collection<StorPool> storPools = getStorPools(peerRscDataRef);
            for (StorPool sp : storPools)
            {
                prioProps.addProps(sp.getProps());
            }

            prioProps.addProps(rsc.getProps());
            prioProps.addProps(rsc.getResourceDefinition().getProps());
            prioProps.addProps(rsc.getResourceDefinition().getResourceGroup().getProps());
            prioProps.addProps(node.getProps());
            prioProps.addProps(stltPropsRef);

            String prefNic = prioProps.getProp(ApiConsts.KEY_STOR_POOL_PREF_NIC);

            if (prefNic != null)
            {
                preferredNetIf = node.getNetInterface(
                    new NetInterfaceName(prefNic)
                );

                if (preferredNetIf == null)
                {
                    errorReporterRef.logWarning(
                        String.format("Preferred network interface '%s' not found, fallback to default", prefNic)
                    );
                }
            }

            // fallback if preferred couldn't be found
            if (preferredNetIf == null)
            {
                // Try to find the 'default' network interface
                preferredNetIf = node.getNetInterface(NetInterfaceName.DEFAULT_NET_INTERFACE_NAME);
                // If there is not even a 'default', use the first one that is found in the node's
                // list of network interfaces
                if (preferredNetIf == null)
                {
                    preferredNetIf = node.streamNetInterfaces().findFirst().orElse(null);
                }
            }
        }
        catch (InvalidKeyException | InvalidNameException implError)
        {
            throw new ImplementationError(implError);
        }

        return preferredNetIf;
    }

    /**
     * Checks the priority props of rsc, rd, rg, all related SPs, node and ctrl if
     * {@value ApiConsts#KEY_STOR_POOL_OUTSIDE_ADDRESS} is set. If it is, returns the corresponding
     * {@link NetInterface} (if it exists) of the current node.
     * <br/>
     *  Returns <code>null</code> if either the <code>NetInterface</code> does not exist or the property is not set.
     */
    private @Nullable NetInterface getOutsideNetIf(DrbdRscData<Resource> peerRscDataRef)
    {
        NetInterface ret = null;
        try
        {
            PriorityProps prioProps = new PriorityProps();

            Resource rsc = peerRscDataRef.getAbsResource();
            Node node = rsc.getNode();

            prioProps.addProps(rsc.getProps());
            prioProps.addProps(rsc.getResourceDefinition().getProps());
            prioProps.addProps(rsc.getResourceDefinition().getResourceGroup().getProps());

            Collection<StorPool> storPools = getStorPools(peerRscDataRef);
            for (StorPool sp : storPools)
            {
                prioProps.addProps(sp.getProps());
            }

            prioProps.addProps(node.getProps());
            prioProps.addProps(stltProps);

            String outsideAddress = prioProps.getProp(
                ApiConsts.KEY_DRBD_OUTSIDE_ADDRESS,
                ApiConsts.NAMESPC_LINSTOR_DRBD
            );
            if (outsideAddress != null)
            {
                ret = node.getNetInterface(
                    new NetInterfaceName(outsideAddress)
                );
            }
        }
        catch (InvalidKeyException | InvalidNameException implError)
        {
            throw new ImplementationError(implError);
        }
        return ret;
    }

    private static LinkedHashSet<StorPool> getStorPools(DrbdRscData<Resource> peerRscDataRef)
    {
        LinkedHashSet<StorPool> ret = new LinkedHashSet<>();

        TreeMap<VolumeNumber, DrbdVlmData<Resource>> sortedVlmData = new TreeMap<>(
            peerRscDataRef.getVlmLayerObjects()
        );
        Entry<VolumeNumber, DrbdVlmData<Resource>> firstVolumeEntry = sortedVlmData.firstEntry();
        if (firstVolumeEntry != null)
        {
            VolumeNumber firstVlmNr = firstVolumeEntry.getKey();
            List<AbsRscLayerObject<Resource>> storageRscList = LayerUtils.getChildLayerDataByKind(
                firstVolumeEntry.getValue().getRscLayerObject(),
                DeviceLayerKind.STORAGE
            );
            for (AbsRscLayerObject<Resource> rscObj : storageRscList)
            {
                VlmProviderObject<Resource> vlmProviderObject = rscObj.getVlmProviderObject(firstVlmNr);
                if (vlmProviderObject != null)
                {
                    // TODO: why not include all storage pools (in a set to remove duplicates)?
                    ret.add(vlmProviderObject.getStorPool());
                }
            }
        }
        return ret;
    }

    private void appendVlmIfPresent(DrbdVlmData<Resource> vlmData, boolean isPeerRsc)
    {
        if (((Volume) vlmData.getVolume()).getFlags().isUnset(Volume.Flags.DELETE))
        {
            final String disk;
            if ((!isPeerRsc && vlmData.getDataDevice() == null) ||
                (isPeerRsc &&
                // FIXME: vlmData.getRscLayerObject().getFlags should be used here
                     vlmData.getVolume().getAbsResource().disklessForDrbdPeers()
                ) ||
                (!isPeerRsc &&
                // FIXME: vlmData.getRscLayerObject().getFlags should be used here
                     vlmData.getVolume().getAbsResource().isDrbdDiskless()
                )
            )
            {
                disk = "none";
            }
            else
            {
                if (!isPeerRsc)
                {
                    String backingDiskPath = vlmData.getDataDevice();
                    if (backingDiskPath.trim().isEmpty())
                    {
                        throw new LinStorRuntimeException(
                            String.format(
                                "Cannot write the DRBD configuration file for resource '%s', " +
                                    "volume %d, because the path of the backing block device is empty",
                                vlmData.getRscLayerObject().getSuffixedResourceName(),
                                vlmData.getVlmNr().value
                            ),
                            DrbdLayer.getAbortMsg(vlmData.getRscLayerObject()),
                            "The layer below DRBD did not report a usable device path for this " +
                                "volume. In most cases an earlier step of this operation failed " +
                                "to create or activate the backing device, or an external " +
                                "storage command reported no device path for it.",
                            "Check the error reports on this satellite for errors that occurred " +
                                "before this one and resolve those first. If no earlier error " +
                                "was reported, create an SOS report before reporting the problem.",
                            vlmData.getVolume().toString()
                        );
                    }
                    disk = backingDiskPath;
                }
                else
                {
                    // Do not use the backing disk path from the peer resource because it may be 'none' when
                    // the peer resource is converting from diskless, but the path here should not be 'none'
                    disk = PEER_DISK_PLACEHOLDER;
                }
            }
            final String metaDisk;
            if (vlmData.getMetaDiskPath() == null)
            {
                metaDisk = "internal";
            }
            else
            {
                String tmpMeta = vlmData.getMetaDiskPath();
                if (tmpMeta.trim().isEmpty())
                {
                    metaDisk = "internal";
                }
                else
                {
                    metaDisk = vlmData.getMetaDiskPath();
                }
            }

            final VolumeDefinition vlmDfn = vlmData.getVolume().getVolumeDefinition();
            VolumeNumber vlmNr = vlmDfn.getVolumeNumber();
            appendLine("volume %s", vlmNr.value);
            try (Section volumeSection = new Section())
            {
                if (PEER_DISK_PLACEHOLDER.equals(disk))
                {
                    appendLine("# The disk path below is a placeholder: this node never opens a peer's");
                    appendLine("# backing device, DRBD only needs to know that the peer has one.");
                }
                appendLine("disk        %s;", disk);

                if (drbdVersionSupportsTiebreaker())
                {
                    appendLine(
                        "tiebreaker %s;",
                        vlmData.getRscLayerObject().getFlags().isSet(DrbdRscFlags.CLIENT) ? "no" : "yes"
                    );
                }
                else
                {
                    appendLine(
                        "# tiebreaker yes;   # DRBD utils: %s, kmod: %s",
                        drbdVersion.getUtilsVsn(),
                        drbdVersion.getKModVsn()
                    );
                }

                ResourceDefinition rscDfn = vlmDfn.getResourceDefinition();
                ResourceGroup rscGrp = rscDfn.getResourceGroup();
                ReadOnlyProps rscDfnProps = rscDfn.getProps();
                PriorityProps vlmPrioProps = new PriorityProps()
                    .addProps(
                        ((Volume) vlmData.getVolume()).getProps(),
                        "V (" + rscDfn.getName() + "/" + vlmNr.value + ")"
                    )
                    .addProps(vlmData.getVolume().getAbsResource().getProps(), "R (" + rscDfn.getName() + ")")
                    .addProps(
                        vlmDfn.getProps(),
                        "VD (" + rscDfn.getName() + "/" + vlmNr.value + ")"
                    )
                    .addProps(
                        rscGrp.getVolumeGroupProps(vlmNr),
                        "VG (" + rscGrp.getName() + "/" + vlmNr.value + ")"
                    )
                    .addProps(rscDfnProps, "RD (" + rscDfn.getName() + ")")
                    .addProps(rscGrp.getProps(), "RG (" + rscGrp.getName() + ")")
                    .addProps(
                        vlmData.getVolume().getAbsResource().getNode().getProps(),
                        "N (" + rscDfn.getName() + ")"
                    )
                    .addProps(stltProps, "C");
                if (vlmPrioProps.anyPropsHasNamespace(ApiConsts.NAMESPC_DRBD_DISK_OPTIONS))
                {
                    appendLine("disk");
                    try (Section ignore = new Section())
                    {
                        appendConflictingDrbdOptions(
                            LinStorObject.CTRL,
                            ApiConsts.NAMESPC_DRBD_DISK_OPTIONS,
                            vlmPrioProps,
                            new ConfFileBuilderAutoRules(vlmData),
                            isPeerRsc
                        );

                        // deliberately not asking the prio-props here, just the RD props
                        @Nullable String exactSize = rscDfnProps.getProp(
                            ApiConsts.KEY_DRBD_EXACT_SIZE,
                            ApiConsts.NAMESPC_DRBD_OPTIONS
                        );
                        if (exactSize != null && Boolean.parseBoolean(exactSize))
                        {
                            appendLine("size    %sk;", Long.toString(vlmDfn.getVolumeSize()));
                        }
                    }
                }

                appendLine("meta-disk   %s;", metaDisk);
                appendLine("device      minor %d;",
                    vlmData.getVlmDfnLayerObject().getMinorNr().value
                // TODO: impl and ask storPool for device
                );
                // TODO: add "disk { ... }" section
            }
        }
    }

    @SuppressWarnings("checkstyle:MagicNumber")
    private boolean drbdVersionSupportsTiebreaker()
    {
        return drbdVersion.getKModVsn().greaterOrEqual(9, 3, 1) &&
            drbdVersion.getUtilsVsn().greaterOrEqual(9, 34, 0);
    }

    private void appendIndent()
    {
        appendIndent(stringBuilder);
    }

    private void appendIndent(StringBuilder sbRef)
    {
        for (int idx = 0; idx < indentDepth; idx++)
        {
            sbRef.append("    ");
        }
    }

    private void append(String format, Object... args)
    {
        stringBuilder.append(String.format(format, args));
    }

    private void appendLine(String format, Object... args)
    {
        appendIndent();
        append(format, args);
        stringBuilder.append("\n");
    }

    private static class ResourceNameComparator implements Comparator<DrbdRscData<?>>
    {
        @Override
        public int compare(DrbdRscData<?> o1, DrbdRscData<?> o2)
        {
            return o1.getAbsResource().getNode().getName().compareTo(
                   o2.getAbsResource().getNode().getName()
            );
        }
    }

    /**
     * Allows a section to be expressed using try-with-resources so that it is automatically closed.
     * <p>
     * Non-static to allow access to the indentDepth.
     */
    private class Section implements AutoCloseable
    {
        Section()
        {
            appendLine("{");
            indentDepth++;
        }

        @Override
        public void close()
        {
            indentDepth--;
            appendLine("}");
        }
    }
}
