---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "ebsremotes.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
  - name: "v1-27-1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              name:
                type: "string"
              dsp_name:
                type: "string"
              flags:
                type: "integer"
                format: "int64"
              url:
                type: "string"
              region:
                type: "string"
              availability_zone:
                type: "string"
              access_key:
                type: "string"
                format: "byte"
              secret_key:
                type: "string"
                format: "byte"
  - name: "v1-25-1"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              name:
                type: "string"
              dsp_name:
                type: "string"
              flags:
                type: "integer"
                format: "int64"
              url:
                type: "string"
              region:
                type: "string"
              availability_zone:
                type: "string"
              access_key:
                type: "string"
                format: "byte"
              secret_key:
                type: "string"
                format: "byte"
  - name: "v1-19-1"
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: "object"
        properties:
          spec:
            type: "object"
            properties:
              uuid:
                type: "string"
              name:
                type: "string"
              dsp_name:
                type: "string"
              flags:
                type: "integer"
                format: "int64"
              url:
                type: "string"
              region:
                type: "string"
              availability_zone:
                type: "string"
              access_key:
                type: "string"
                format: "byte"
              secret_key:
                type: "string"
                format: "byte"
  scope: "Cluster"
  names:
    plural: "ebsremotes"
    singular: "ebsremotes"
    kind: "EbsRemotes"
