CREATE TABLE SNAPSHOT_DEFINITIONS
(
    UUID CHARACTER(36) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_DSP_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_FLAGS BIGINT NOT NULL,
    CONSTRAINT PK_SD PRIMARY KEY (RESOURCE_NAME, SNAPSHOT_NAME),
    CONSTRAINT FK_SD_RSC_DFN FOREIGN KEY (RESOURCE_NAME) REFERENCES RESOURCE_DEFINITIONS(RESOURCE_NAME),
    CONSTRAINT UNQ_SD_UUID UNIQUE (UUID)
);
