CREATE TABLE LAYER_DRBD_VOLUMES
(
    LAYER_RESOURCE_ID INTEGER NOT NULL,
    VLM_NR INTEGER NOT NULL,
    NODE_NAME VARCHAR(255), -- null when using internal meta-data
    POOL_NAME VARCHAR(48),  -- null when using internal meta-data
    CONSTRAINT PK_LDV PRIMARY KEY (LAYER_RESOURCE_ID, VLM_NR),
    CONSTRAINT FK_LDV_LRI FOREIGN KEY (LAYER_RESOURCE_ID) REFERENCES LAYER_RESOURCE_IDS(LAYER_RESOURCE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LDV_NSP FOREIGN KEY (NODE_NAME, POOL_NAME) REFERENCES NODE_STOR_POOL(NODE_NAME, POOL_NAME) ON DELETE CASCADE
);

