-- Temporary table created by the migration's Java class
-- (Migration_2018_10_08_ResourceConn_Flags.java)
-- For most databases:
--     CREATE TABLE RESOURCE_CONNECTIONS_TMP AS SELECT * FROM RESOURCE_CONNECTIONS;
-- For DB2:
--     CREATE TABLE RESOURCE_CONNECTIONS_TMP AS SELECT * FROM RESOURCE_CONNECTIONS WITH DATA;
DROP TABLE RESOURCE_DEFINITIONS;
CREATE TABLE RESOURCE_DEFINITIONS
(
    UUID CHARACTER(36) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    RESOURCE_DSP_NAME VARCHAR(48) NOT NULL,
    RESOURCE_FLAGS BIGINT NOT NULL,
    LAYER_STACK VARCHAR(1024) NOT NULL,
    CONSTRAINT PK_RD PRIMARY KEY (RESOURCE_NAME),
    CONSTRAINT UNQ_RD_UUID UNIQUE (UUID),
    CONSTRAINT CHK_RD_NAME CHECK (UPPER(RESOURCE_NAME) = RESOURCE_NAME AND LENGTH(RESOURCE_NAME) >= 2),
    CONSTRAINT CHK_RD_DSP_NAME CHECK (UPPER(RESOURCE_DSP_NAME) = RESOURCE_NAME)    
);

INSERT INTO RESOURCE_DEFINITIONS SELECT UUID, RESOURCE_NAME, RESOURCE_DSP_NAME, RESOURCE_FLAGS, '[]' FROM RESOURCE_DEFINITIONS_TMP;

DROP TABLE SNAPSHOTS;
CREATE TABLE SNAPSHOTS
(
    UUID CHARACTER(36) NOT NULL,
    NODE_NAME VARCHAR(255) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_FLAGS BIGINT NOT NULL,
    NODE_ID INTEGER NULL, -- nullable
    LAYER_STACK VARCHAR(1024) NOT NULL,
    CONSTRAINT PK_S PRIMARY KEY (NODE_NAME, RESOURCE_NAME, SNAPSHOT_NAME),
    CONSTRAINT FK_S_NODES FOREIGN KEY (NODE_NAME) REFERENCES NODES(NODE_NAME),
    CONSTRAINT FK_S_SNAPSHOT_DFN FOREIGN KEY (RESOURCE_NAME, SNAPSHOT_NAME)
        REFERENCES SNAPSHOT_DEFINITIONS(RESOURCE_NAME, SNAPSHOT_NAME),
    CONSTRAINT UNQ_S_UUID UNIQUE (UUID)
);

INSERT INTO SNAPSHOTS SELECT UUID, NODE_NAME, RESOURCE_NAME, SNAPSHOT_NAME, SNAPSHOT_FLAGS, NODE_ID, '[]' FROM SNAPSHOTS_TMP;

DROP TABLE RESOURCE_DEFINITIONS_TMP;
DROP TABLE SNAPSHOTS_TMP;

