-- Temporary table created by the migration's Java class
-- (Migration_2019_03_06_RscDfn_LayerStack.java)
-- For most databases:
--     CREATE TABLE RESOURCE_DEFINITIONS_TMP AS SELECT * FROM RESOURCE_DEFINITIONS;
--     CREATE TABLE SNAPSHOTS_TMP AS SELECT * FROM SNAPSHOTS;
-- For DB2:
--     CREATE TABLE RESOURCE_DEFINITIONS_TMP AS (SELECT * FROM RESOURCE_DEFINITIONS) WITH DATA;
--     CREATE TABLE SNAPSHOTS_TMP AS (SELECT * FROM SNAPSHOTS) WITH DATA;

-- FIXME: This drops various foreign key constraints from other tables
DROP TABLE RESOURCE_DEFINITIONS;
CREATE TABLE RESOURCE_DEFINITIONS
(
    UUID CHARACTER(36) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    RESOURCE_DSP_NAME VARCHAR(48) NOT NULL,
    RESOURCE_FLAGS BIGINT NOT NULL,
    LAYER_STACK VARCHAR(1024) NOT NULL,
    CONSTRAINT PK_RD PRIMARY KEY (RESOURCE_NAME),
    CONSTRAINT UNQ_RD_UUID UNIQUE (UUID),
    CONSTRAINT CHK_RD_NAME CHECK (UPPER(RESOURCE_NAME) = RESOURCE_NAME AND LENGTH(RESOURCE_NAME) >= 2),
    CONSTRAINT CHK_RD_DSP_NAME CHECK (UPPER(RESOURCE_DSP_NAME) = RESOURCE_NAME)
);

INSERT INTO RESOURCE_DEFINITIONS
    (SELECT UUID, RESOURCE_NAME, RESOURCE_DSP_NAME, RESOURCE_FLAGS, '[]' FROM RESOURCE_DEFINITIONS_TMP);

-- FIXME: This drops various foreign key constraints from other tables
DROP TABLE SNAPSHOTS;
CREATE TABLE SNAPSHOTS
(
    UUID CHARACTER(36) NOT NULL,
    NODE_NAME VARCHAR(255) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_FLAGS BIGINT NOT NULL,
    NODE_ID INTEGER NULL, -- nullable
    LAYER_STACK VARCHAR(1024) NOT NULL,
    CONSTRAINT PK_S PRIMARY KEY (NODE_NAME, RESOURCE_NAME, SNAPSHOT_NAME),
    CONSTRAINT FK_S_NODES FOREIGN KEY (NODE_NAME) REFERENCES NODES(NODE_NAME),
    CONSTRAINT FK_S_SNAPSHOT_DFN FOREIGN KEY (RESOURCE_NAME, SNAPSHOT_NAME)
        REFERENCES SNAPSHOT_DEFINITIONS(RESOURCE_NAME, SNAPSHOT_NAME),
    CONSTRAINT UNQ_S_UUID UNIQUE (UUID)
);


