-- Temporary table created by the migration's Java class
-- (Migration_2019_02_20_LayerData.java)
-- For most databases:
--     CREATE TABLE RESOURCE_DEFINITIONS_TMP AS SELECT * FROM RESOURCE_DEFINITIONS;
--     CREATE TABLE RESOURCES_TMP AS SELECT * FROM RESOURCES;
--     CREATE TABLE VOLUME_DEFINITIONS_TMP AS SELECT * FROM VOLUME_DEFINITIONS;
-- For DB2:
--     CREATE TABLE RESOURCE_DEFINITIONS_TMP AS (SELECT * FROM RESOURCE_DEFINITIONS) WITH DATA;
--     CREATE TABLE RESOURCES_TMP AS (SELECT * FROM RESOURCES) WITH DATA;
--     CREATE TABLE VOLUME_DEFINITIONS_TMP AS (SELECT * FROM VOLUME_DEFINITIONS) WITH DATA;

-- FIXME: This drops various foreign key constraints from other tables
DROP TABLE RESOURCE_DEFINITIONS;
CREATE TABLE RESOURCE_DEFINITIONS
(
    UUID CHARACTER(36) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    RESOURCE_DSP_NAME VARCHAR(48) NOT NULL,
    RESOURCE_FLAGS BIGINT NOT NULL,
    CONSTRAINT PK_RD PRIMARY KEY (RESOURCE_NAME),
    CONSTRAINT UNQ_RD_UUID UNIQUE (UUID),
    CONSTRAINT CHK_RD_NAME CHECK (UPPER(RESOURCE_NAME) = RESOURCE_NAME AND LENGTH(RESOURCE_NAME) >= 2),
    CONSTRAINT CHK_RD_DSP_NAME CHECK (UPPER(RESOURCE_DSP_NAME) = RESOURCE_NAME)
);

INSERT INTO RESOURCE_DEFINITIONS SELECT UUID, RESOURCE_NAME, RESOURCE_DSP_NAME, RESOURCE_FLAGS FROM RESOURCE_DEFINITIONS_TMP;

-- FIXME: This drops various foreign key constraints from other tables
DROP TABLE RESOURCES;
CREATE TABLE RESOURCES
(
    UUID CHARACTER(36) NOT NULL,
    NODE_NAME VARCHAR(255) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    RESOURCE_FLAGS BIGINT NOT NULL,
    CONSTRAINT PK_R PRIMARY KEY (NODE_NAME, RESOURCE_NAME),
    CONSTRAINT FK_R_NODES FOREIGN KEY (NODE_NAME) REFERENCES NODES(NODE_NAME) ON DELETE CASCADE,
    CONSTRAINT FK_R_RSC_DFNS FOREIGN KEY (RESOURCE_NAME) REFERENCES RESOURCE_DEFINITIONS(RESOURCE_NAME)
        ON DELETE CASCADE,
    CONSTRAINT UNQ_R_UUID UNIQUE (UUID)
);

INSERT INTO RESOURCES SELECT UUID, NODE_NAME, RESOURCE_NAME, RESOURCE_FLAGS FROM RESOURCES_TMP;

-- FIXME: This drops various foreign key constraints from other tables
DROP TABLE VOLUME_DEFINITIONS;
CREATE TABLE VOLUME_DEFINITIONS
(
    UUID CHARACTER(36) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    VLM_NR INTEGER NOT NULL,
    VLM_SIZE BIGINT NOT NULL,
    VLM_FLAGS BIGINT NOT NULL,
    CONSTRAINT PK_VD PRIMARY KEY (RESOURCE_NAME, VLM_NR),
    CONSTRAINT FK_VD_RSC_DFN FOREIGN KEY (RESOURCE_NAME) REFERENCES RESOURCE_DEFINITIONS(RESOURCE_NAME)
        ON DELETE CASCADE,
    CONSTRAINT UNQ_VD_UUID UNIQUE (UUID)
);
INSERT INTO VOLUME_DEFINITIONS SELECT UUID, RESOURCE_NAME, VLM_NR, VLM_SIZE, VLM_FLAGS FROM VOLUME_DEFINITIONS_TMP;

DROP TABLE RESOURCE_DEFINITIONS_TMP;
DROP TABLE RESOURCES_TMP;
DROP TABLE VOLUME_DEFINITIONS_TMP;

