CREATE TABLE LAYER_WRITECACHE_VOLUMES
(
    LAYER_RESOURCE_ID INTEGER NOT NULL,
    VLM_NR INTEGER NOT NULL,
    NODE_NAME VARCHAR(255) NOT NULL,
    POOL_NAME VARCHAR(48) NOT NULL,
    CONSTRAINT PK_LWV PRIMARY KEY (LAYER_RESOURCE_ID, VLM_NR),
    CONSTRAINT FK_LWV_LRI FOREIGN KEY (LAYER_RESOURCE_ID) REFERENCES LAYER_RESOURCE_IDS(LAYER_RESOURCE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LWV_NSP FOREIGN KEY (NODE_NAME, POOL_NAME) REFERENCES NODE_STOR_POOL(NODE_NAME, POOL_NAME) ON DELETE CASCADE
);

