CREATE TABLE LAYER_CACHE_VOLUMES
(
    LAYER_RESOURCE_ID INTEGER NOT NULL,
    VLM_NR INTEGER NOT NULL,
    NODE_NAME VARCHAR(255) NOT NULL,
    POOL_NAME_CACHE VARCHAR(48) NOT NULL,
    POOL_NAME_META VARCHAR(48) NOT NULL,
    CONSTRAINT PK_LCV PRIMARY KEY (LAYER_RESOURCE_ID, VLM_NR),
    CONSTRAINT FK_LCV_LRI FOREIGN KEY (LAYER_RESOURCE_ID) REFERENCES LAYER_RESOURCE_IDS(LAYER_RESOURCE_ID),
    CONSTRAINT FK_LCV_NSP_C FOREIGN KEY (NODE_NAME, POOL_NAME_CACHE) REFERENCES NODE_STOR_POOL(NODE_NAME, POOL_NAME),
    CONSTRAINT FK_LCV_NSP_M FOREIGN KEY (NODE_NAME, POOL_NAME_META) REFERENCES NODE_STOR_POOL(NODE_NAME, POOL_NAME)
);

