-- Create tables for SpaceTracking
CREATE TABLE SATELLITES_CAPACITY (
    NODE_NAME VARCHAR(48) NOT NULL PRIMARY KEY,
    CAPACITY BLOB NOT NULL,
    FAIL_FLAG BOOLEAN NOT NULL
);

CREATE TABLE TRACKING_DATE (ENTRY_DATE DATE NOT NULL);

CREATE TABLE SPACE_HISTORY (
    ENTRY_DATE DATE NOT NULL PRIMARY KEY,
    CAPACITY BLOB NOT NULL
);
