-- create tables for remotes
CREATE TABLE SCHEDULES(
    UUID CHARACTER(36) NOT NULL,
    NAME VARCHAR(256) NOT NULL PRIMARY KEY,
    DSP_NAME VARCHAR(256) NOT NULL,
    FLAGS BIGINT NOT NULL,
    FULL_CRON VARCHAR(256) NOT NULL,
    INC_CRON VARCHAR(256), -- nullable
    KEEP_LOCAL INTEGER, -- nullable
    KEEP_REMOTE INTEGER, -- nullable
    ON_FAILURE BIGINT NOT NULL,
    MAX_RETRIES INTEGER -- nullable
);