-- create tables for auth tokens
CREATE TABLE AUTH_TOKENS(
    ID INTEGER NOT NULL PRIMARY KEY,
    TOKEN_HASH CHARACTER(64) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP NULL DEFAULT NULL,
    EXPIRES_AT TIMESTAMP NULL DEFAULT NULL,
    IP_FILTER VARCHAR(256) NULL,
    IS_USER_TOKEN BOOLEAN DEFAULT FALSE NOT NULL -- auto-generated or from user
);
