---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "authtokens.internal.linstor.linbit.com"
spec:
  group: "internal.linstor.linbit.com"
  versions:
    - name: "v1-33-1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: "object"
          properties:
            spec:
              type: "object"
              properties:
                id:
                  type: "integer"
                  format: "int32"
                token_hash:
                  type: "string"
                description:
                  type: "string"
                is_active:
                  type: "boolean"
                created_at:
                  type: "integer"
                  format: "int64"
                deleted_at:
                  type: "integer"
                  format: "int64"
                expires_at:
                  type: "integer"
                  format: "int64"
                ip_filter:
                  type: "string"
                is_user_token:
                  type: "boolean"
  scope: "Cluster"
  names:
    plural: "authtokens"
    singular: "authtokens"
    kind: "AuthTokens"
