CREATE TABLE SNAPSHOTS
(
    UUID CHAR(36) NOT NULL,
    NODE_NAME VARCHAR(255) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_NAME VARCHAR(48) NOT NULL,
    CONSTRAINT PK_S PRIMARY KEY (NODE_NAME, RESOURCE_NAME, SNAPSHOT_NAME),
    CONSTRAINT FK_S_NODES FOREIGN KEY (NODE_NAME) REFERENCES NODES(NODE_NAME),
    CONSTRAINT FK_S_SNAPSHOT_DFN FOREIGN KEY (RESOURCE_NAME, SNAPSHOT_NAME)
        REFERENCES SNAPSHOT_DEFINITIONS(RESOURCE_NAME, SNAPSHOT_NAME),
    CONSTRAINT UNQ_S_UUID UNIQUE (UUID)
);

CREATE TABLE SNAPSHOT_VOLUME_DEFINITIONS
(
    UUID CHAR(36) NOT NULL,
    RESOURCE_NAME VARCHAR(48) NOT NULL,
    SNAPSHOT_NAME VARCHAR(48) NOT NULL,
    VLM_NR INT NOT NULL,
    CONSTRAINT PK_SVD PRIMARY KEY (RESOURCE_NAME, SNAPSHOT_NAME, VLM_NR),
    CONSTRAINT FK_SVD_SNAPSHOT_DFN FOREIGN KEY (RESOURCE_NAME, SNAPSHOT_NAME)
        REFERENCES SNAPSHOT_DEFINITIONS(RESOURCE_NAME, SNAPSHOT_NAME),
    CONSTRAINT UNQ_SVD_UUID UNIQUE (UUID)
);

