// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgCrtVlmDfn.proto

package com.linbit.drbdmanage.proto;

public final class MsgCrtVlmDfnOuterClass {
  private MsgCrtVlmDfnOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgCrtVlmDfnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.linbit.drbdmanage.proto.MsgCrtVlmDfn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Resource name
     * </pre>
     *
     * <code>string rsc_name = 1;</code>
     */
    java.lang.String getRscName();
    /**
     * <pre>
     * Resource name
     * </pre>
     *
     * <code>string rsc_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getRscNameBytes();

    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn> 
        getVlmDfnMapList();
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn getVlmDfnMap(int index);
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    int getVlmDfnMapCount();
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    java.util.List<? extends com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder> 
        getVlmDfnMapOrBuilderList();
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder getVlmDfnMapOrBuilder(
        int index);
  }
  /**
   * <pre>
   * drbdmanageNG - Create volume definition
   * </pre>
   *
   * Protobuf type {@code com.linbit.drbdmanage.proto.MsgCrtVlmDfn}
   */
  public  static final class MsgCrtVlmDfn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.linbit.drbdmanage.proto.MsgCrtVlmDfn)
      MsgCrtVlmDfnOrBuilder {
    // Use MsgCrtVlmDfn.newBuilder() to construct.
    private MsgCrtVlmDfn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgCrtVlmDfn() {
      rscName_ = "";
      vlmDfnMap_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MsgCrtVlmDfn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              rscName_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                vlmDfnMap_ = new java.util.ArrayList<com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn>();
                mutable_bitField0_ |= 0x00000002;
              }
              vlmDfnMap_.add(
                  input.readMessage(com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          vlmDfnMap_ = java.util.Collections.unmodifiableList(vlmDfnMap_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn.class, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn.Builder.class);
    }

    private int bitField0_;
    public static final int RSC_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object rscName_;
    /**
     * <pre>
     * Resource name
     * </pre>
     *
     * <code>string rsc_name = 1;</code>
     */
    public java.lang.String getRscName() {
      java.lang.Object ref = rscName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rscName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Resource name
     * </pre>
     *
     * <code>string rsc_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRscNameBytes() {
      java.lang.Object ref = rscName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rscName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VLM_DFN_MAP_FIELD_NUMBER = 2;
    private java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn> vlmDfnMap_;
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    public java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn> getVlmDfnMapList() {
      return vlmDfnMap_;
    }
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    public java.util.List<? extends com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder> 
        getVlmDfnMapOrBuilderList() {
      return vlmDfnMap_;
    }
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    public int getVlmDfnMapCount() {
      return vlmDfnMap_.size();
    }
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn getVlmDfnMap(int index) {
      return vlmDfnMap_.get(index);
    }
    /**
     * <pre>
     * Volume definitions to add to the resource
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
     */
    public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder getVlmDfnMapOrBuilder(
        int index) {
      return vlmDfnMap_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRscNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rscName_);
      }
      for (int i = 0; i < vlmDfnMap_.size(); i++) {
        output.writeMessage(2, vlmDfnMap_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRscNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rscName_);
      }
      for (int i = 0; i < vlmDfnMap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, vlmDfnMap_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn)) {
        return super.equals(obj);
      }
      com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn other = (com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn) obj;

      boolean result = true;
      result = result && getRscName()
          .equals(other.getRscName());
      result = result && getVlmDfnMapList()
          .equals(other.getVlmDfnMapList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RSC_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getRscName().hashCode();
      if (getVlmDfnMapCount() > 0) {
        hash = (37 * hash) + VLM_DFN_MAP_FIELD_NUMBER;
        hash = (53 * hash) + getVlmDfnMapList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * drbdmanageNG - Create volume definition
     * </pre>
     *
     * Protobuf type {@code com.linbit.drbdmanage.proto.MsgCrtVlmDfn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.linbit.drbdmanage.proto.MsgCrtVlmDfn)
        com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn.class, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn.Builder.class);
      }

      // Construct using com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVlmDfnMapFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        rscName_ = "";

        if (vlmDfnMapBuilder_ == null) {
          vlmDfnMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          vlmDfnMapBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_descriptor;
      }

      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn getDefaultInstanceForType() {
        return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn.getDefaultInstance();
      }

      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn build() {
        com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn buildPartial() {
        com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn result = new com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.rscName_ = rscName_;
        if (vlmDfnMapBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            vlmDfnMap_ = java.util.Collections.unmodifiableList(vlmDfnMap_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.vlmDfnMap_ = vlmDfnMap_;
        } else {
          result.vlmDfnMap_ = vlmDfnMapBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn) {
          return mergeFrom((com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn other) {
        if (other == com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn.getDefaultInstance()) return this;
        if (!other.getRscName().isEmpty()) {
          rscName_ = other.rscName_;
          onChanged();
        }
        if (vlmDfnMapBuilder_ == null) {
          if (!other.vlmDfnMap_.isEmpty()) {
            if (vlmDfnMap_.isEmpty()) {
              vlmDfnMap_ = other.vlmDfnMap_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureVlmDfnMapIsMutable();
              vlmDfnMap_.addAll(other.vlmDfnMap_);
            }
            onChanged();
          }
        } else {
          if (!other.vlmDfnMap_.isEmpty()) {
            if (vlmDfnMapBuilder_.isEmpty()) {
              vlmDfnMapBuilder_.dispose();
              vlmDfnMapBuilder_ = null;
              vlmDfnMap_ = other.vlmDfnMap_;
              bitField0_ = (bitField0_ & ~0x00000002);
              vlmDfnMapBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVlmDfnMapFieldBuilder() : null;
            } else {
              vlmDfnMapBuilder_.addAllMessages(other.vlmDfnMap_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object rscName_ = "";
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 1;</code>
       */
      public java.lang.String getRscName() {
        java.lang.Object ref = rscName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rscName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRscNameBytes() {
        java.lang.Object ref = rscName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rscName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 1;</code>
       */
      public Builder setRscName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rscName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 1;</code>
       */
      public Builder clearRscName() {
        
        rscName_ = getDefaultInstance().getRscName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 1;</code>
       */
      public Builder setRscNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rscName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn> vlmDfnMap_ =
        java.util.Collections.emptyList();
      private void ensureVlmDfnMapIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          vlmDfnMap_ = new java.util.ArrayList<com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn>(vlmDfnMap_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder> vlmDfnMapBuilder_;

      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn> getVlmDfnMapList() {
        if (vlmDfnMapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vlmDfnMap_);
        } else {
          return vlmDfnMapBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public int getVlmDfnMapCount() {
        if (vlmDfnMapBuilder_ == null) {
          return vlmDfnMap_.size();
        } else {
          return vlmDfnMapBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn getVlmDfnMap(int index) {
        if (vlmDfnMapBuilder_ == null) {
          return vlmDfnMap_.get(index);
        } else {
          return vlmDfnMapBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder setVlmDfnMap(
          int index, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn value) {
        if (vlmDfnMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVlmDfnMapIsMutable();
          vlmDfnMap_.set(index, value);
          onChanged();
        } else {
          vlmDfnMapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder setVlmDfnMap(
          int index, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder builderForValue) {
        if (vlmDfnMapBuilder_ == null) {
          ensureVlmDfnMapIsMutable();
          vlmDfnMap_.set(index, builderForValue.build());
          onChanged();
        } else {
          vlmDfnMapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder addVlmDfnMap(com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn value) {
        if (vlmDfnMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVlmDfnMapIsMutable();
          vlmDfnMap_.add(value);
          onChanged();
        } else {
          vlmDfnMapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder addVlmDfnMap(
          int index, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn value) {
        if (vlmDfnMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVlmDfnMapIsMutable();
          vlmDfnMap_.add(index, value);
          onChanged();
        } else {
          vlmDfnMapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder addVlmDfnMap(
          com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder builderForValue) {
        if (vlmDfnMapBuilder_ == null) {
          ensureVlmDfnMapIsMutable();
          vlmDfnMap_.add(builderForValue.build());
          onChanged();
        } else {
          vlmDfnMapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder addVlmDfnMap(
          int index, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder builderForValue) {
        if (vlmDfnMapBuilder_ == null) {
          ensureVlmDfnMapIsMutable();
          vlmDfnMap_.add(index, builderForValue.build());
          onChanged();
        } else {
          vlmDfnMapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder addAllVlmDfnMap(
          java.lang.Iterable<? extends com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn> values) {
        if (vlmDfnMapBuilder_ == null) {
          ensureVlmDfnMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vlmDfnMap_);
          onChanged();
        } else {
          vlmDfnMapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder clearVlmDfnMap() {
        if (vlmDfnMapBuilder_ == null) {
          vlmDfnMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          vlmDfnMapBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public Builder removeVlmDfnMap(int index) {
        if (vlmDfnMapBuilder_ == null) {
          ensureVlmDfnMapIsMutable();
          vlmDfnMap_.remove(index);
          onChanged();
        } else {
          vlmDfnMapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder getVlmDfnMapBuilder(
          int index) {
        return getVlmDfnMapFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder getVlmDfnMapOrBuilder(
          int index) {
        if (vlmDfnMapBuilder_ == null) {
          return vlmDfnMap_.get(index);  } else {
          return vlmDfnMapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public java.util.List<? extends com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder> 
           getVlmDfnMapOrBuilderList() {
        if (vlmDfnMapBuilder_ != null) {
          return vlmDfnMapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vlmDfnMap_);
        }
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder addVlmDfnMapBuilder() {
        return getVlmDfnMapFieldBuilder().addBuilder(
            com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.getDefaultInstance());
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder addVlmDfnMapBuilder(
          int index) {
        return getVlmDfnMapFieldBuilder().addBuilder(
            index, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.getDefaultInstance());
      }
      /**
       * <pre>
       * Volume definitions to add to the resource
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.VlmDfn vlm_dfn_map = 2;</code>
       */
      public java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder> 
           getVlmDfnMapBuilderList() {
        return getVlmDfnMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder> 
          getVlmDfnMapFieldBuilder() {
        if (vlmDfnMapBuilder_ == null) {
          vlmDfnMapBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder>(
                  vlmDfnMap_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          vlmDfnMap_ = null;
        }
        return vlmDfnMapBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.linbit.drbdmanage.proto.MsgCrtVlmDfn)
    }

    // @@protoc_insertion_point(class_scope:com.linbit.drbdmanage.proto.MsgCrtVlmDfn)
    private static final com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn();
    }

    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgCrtVlmDfn>
        PARSER = new com.google.protobuf.AbstractParser<MsgCrtVlmDfn>() {
      public MsgCrtVlmDfn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgCrtVlmDfn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgCrtVlmDfn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgCrtVlmDfn> getParserForType() {
      return PARSER;
    }

    public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.MsgCrtVlmDfn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VlmDfnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.linbit.drbdmanage.proto.VlmDfn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Volume number
     * -1 for automatic assignment
     * </pre>
     *
     * <code>sint32 vlm_nr = 1;</code>
     */
    int getVlmNr();

    /**
     * <pre>
     * Volume size (in kiB)
     * </pre>
     *
     * <code>int64 vlm_size = 2;</code>
     */
    long getVlmSize();

    /**
     * <pre>
     * Volume minor number
     * </pre>
     *
     * <code>sint32 vlm_minor = 3;</code>
     */
    int getVlmMinor();

    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */
    int getVlmPropsCount();
    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */
    boolean containsVlmProps(
        java.lang.String key);
    /**
     * Use {@link #getVlmPropsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getVlmProps();
    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getVlmPropsMap();
    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */

    java.lang.String getVlmPropsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */

    java.lang.String getVlmPropsOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Embedded volume definition
   * </pre>
   *
   * Protobuf type {@code com.linbit.drbdmanage.proto.VlmDfn}
   */
  public  static final class VlmDfn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.linbit.drbdmanage.proto.VlmDfn)
      VlmDfnOrBuilder {
    // Use VlmDfn.newBuilder() to construct.
    private VlmDfn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VlmDfn() {
      vlmNr_ = 0;
      vlmSize_ = 0L;
      vlmMinor_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VlmDfn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              vlmNr_ = input.readSInt32();
              break;
            }
            case 16: {

              vlmSize_ = input.readInt64();
              break;
            }
            case 24: {

              vlmMinor_ = input.readSInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                vlmProps_ = com.google.protobuf.MapField.newMapField(
                    VlmPropsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              vlmProps__ = input.readMessage(
                  VlmPropsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              vlmProps_.getMutableMap().put(
                  vlmProps__.getKey(), vlmProps__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_VlmDfn_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetVlmProps();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_VlmDfn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.class, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder.class);
    }

    private int bitField0_;
    public static final int VLM_NR_FIELD_NUMBER = 1;
    private int vlmNr_;
    /**
     * <pre>
     * Volume number
     * -1 for automatic assignment
     * </pre>
     *
     * <code>sint32 vlm_nr = 1;</code>
     */
    public int getVlmNr() {
      return vlmNr_;
    }

    public static final int VLM_SIZE_FIELD_NUMBER = 2;
    private long vlmSize_;
    /**
     * <pre>
     * Volume size (in kiB)
     * </pre>
     *
     * <code>int64 vlm_size = 2;</code>
     */
    public long getVlmSize() {
      return vlmSize_;
    }

    public static final int VLM_MINOR_FIELD_NUMBER = 3;
    private int vlmMinor_;
    /**
     * <pre>
     * Volume minor number
     * </pre>
     *
     * <code>sint32 vlm_minor = 3;</code>
     */
    public int getVlmMinor() {
      return vlmMinor_;
    }

    public static final int VLM_PROPS_FIELD_NUMBER = 4;
    private static final class VlmPropsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_VlmDfn_VlmPropsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> vlmProps_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetVlmProps() {
      if (vlmProps_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VlmPropsDefaultEntryHolder.defaultEntry);
      }
      return vlmProps_;
    }

    public int getVlmPropsCount() {
      return internalGetVlmProps().getMap().size();
    }
    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */

    public boolean containsVlmProps(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetVlmProps().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVlmPropsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getVlmProps() {
      return getVlmPropsMap();
    }
    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getVlmPropsMap() {
      return internalGetVlmProps().getMap();
    }
    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */

    public java.lang.String getVlmPropsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetVlmProps().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Volume properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; vlm_props = 4;</code>
     */

    public java.lang.String getVlmPropsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetVlmProps().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vlmNr_ != 0) {
        output.writeSInt32(1, vlmNr_);
      }
      if (vlmSize_ != 0L) {
        output.writeInt64(2, vlmSize_);
      }
      if (vlmMinor_ != 0) {
        output.writeSInt32(3, vlmMinor_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetVlmProps(),
          VlmPropsDefaultEntryHolder.defaultEntry,
          4);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vlmNr_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, vlmNr_);
      }
      if (vlmSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, vlmSize_);
      }
      if (vlmMinor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, vlmMinor_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetVlmProps().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        vlmProps__ = VlmPropsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, vlmProps__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn)) {
        return super.equals(obj);
      }
      com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn other = (com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn) obj;

      boolean result = true;
      result = result && (getVlmNr()
          == other.getVlmNr());
      result = result && (getVlmSize()
          == other.getVlmSize());
      result = result && (getVlmMinor()
          == other.getVlmMinor());
      result = result && internalGetVlmProps().equals(
          other.internalGetVlmProps());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VLM_NR_FIELD_NUMBER;
      hash = (53 * hash) + getVlmNr();
      hash = (37 * hash) + VLM_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVlmSize());
      hash = (37 * hash) + VLM_MINOR_FIELD_NUMBER;
      hash = (53 * hash) + getVlmMinor();
      if (!internalGetVlmProps().getMap().isEmpty()) {
        hash = (37 * hash) + VLM_PROPS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetVlmProps().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Embedded volume definition
     * </pre>
     *
     * Protobuf type {@code com.linbit.drbdmanage.proto.VlmDfn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.linbit.drbdmanage.proto.VlmDfn)
        com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_VlmDfn_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetVlmProps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableVlmProps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_VlmDfn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.class, com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.Builder.class);
      }

      // Construct using com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        vlmNr_ = 0;

        vlmSize_ = 0L;

        vlmMinor_ = 0;

        internalGetMutableVlmProps().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.internal_static_com_linbit_drbdmanage_proto_VlmDfn_descriptor;
      }

      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn getDefaultInstanceForType() {
        return com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.getDefaultInstance();
      }

      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn build() {
        com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn buildPartial() {
        com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn result = new com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.vlmNr_ = vlmNr_;
        result.vlmSize_ = vlmSize_;
        result.vlmMinor_ = vlmMinor_;
        result.vlmProps_ = internalGetVlmProps();
        result.vlmProps_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn) {
          return mergeFrom((com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn other) {
        if (other == com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn.getDefaultInstance()) return this;
        if (other.getVlmNr() != 0) {
          setVlmNr(other.getVlmNr());
        }
        if (other.getVlmSize() != 0L) {
          setVlmSize(other.getVlmSize());
        }
        if (other.getVlmMinor() != 0) {
          setVlmMinor(other.getVlmMinor());
        }
        internalGetMutableVlmProps().mergeFrom(
            other.internalGetVlmProps());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int vlmNr_ ;
      /**
       * <pre>
       * Volume number
       * -1 for automatic assignment
       * </pre>
       *
       * <code>sint32 vlm_nr = 1;</code>
       */
      public int getVlmNr() {
        return vlmNr_;
      }
      /**
       * <pre>
       * Volume number
       * -1 for automatic assignment
       * </pre>
       *
       * <code>sint32 vlm_nr = 1;</code>
       */
      public Builder setVlmNr(int value) {
        
        vlmNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Volume number
       * -1 for automatic assignment
       * </pre>
       *
       * <code>sint32 vlm_nr = 1;</code>
       */
      public Builder clearVlmNr() {
        
        vlmNr_ = 0;
        onChanged();
        return this;
      }

      private long vlmSize_ ;
      /**
       * <pre>
       * Volume size (in kiB)
       * </pre>
       *
       * <code>int64 vlm_size = 2;</code>
       */
      public long getVlmSize() {
        return vlmSize_;
      }
      /**
       * <pre>
       * Volume size (in kiB)
       * </pre>
       *
       * <code>int64 vlm_size = 2;</code>
       */
      public Builder setVlmSize(long value) {
        
        vlmSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Volume size (in kiB)
       * </pre>
       *
       * <code>int64 vlm_size = 2;</code>
       */
      public Builder clearVlmSize() {
        
        vlmSize_ = 0L;
        onChanged();
        return this;
      }

      private int vlmMinor_ ;
      /**
       * <pre>
       * Volume minor number
       * </pre>
       *
       * <code>sint32 vlm_minor = 3;</code>
       */
      public int getVlmMinor() {
        return vlmMinor_;
      }
      /**
       * <pre>
       * Volume minor number
       * </pre>
       *
       * <code>sint32 vlm_minor = 3;</code>
       */
      public Builder setVlmMinor(int value) {
        
        vlmMinor_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Volume minor number
       * </pre>
       *
       * <code>sint32 vlm_minor = 3;</code>
       */
      public Builder clearVlmMinor() {
        
        vlmMinor_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> vlmProps_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetVlmProps() {
        if (vlmProps_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              VlmPropsDefaultEntryHolder.defaultEntry);
        }
        return vlmProps_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableVlmProps() {
        onChanged();;
        if (vlmProps_ == null) {
          vlmProps_ = com.google.protobuf.MapField.newMapField(
              VlmPropsDefaultEntryHolder.defaultEntry);
        }
        if (!vlmProps_.isMutable()) {
          vlmProps_ = vlmProps_.copy();
        }
        return vlmProps_;
      }

      public int getVlmPropsCount() {
        return internalGetVlmProps().getMap().size();
      }
      /**
       * <pre>
       * Volume properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; vlm_props = 4;</code>
       */

      public boolean containsVlmProps(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetVlmProps().getMap().containsKey(key);
      }
      /**
       * Use {@link #getVlmPropsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getVlmProps() {
        return getVlmPropsMap();
      }
      /**
       * <pre>
       * Volume properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; vlm_props = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getVlmPropsMap() {
        return internalGetVlmProps().getMap();
      }
      /**
       * <pre>
       * Volume properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; vlm_props = 4;</code>
       */

      public java.lang.String getVlmPropsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetVlmProps().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Volume properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; vlm_props = 4;</code>
       */

      public java.lang.String getVlmPropsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetVlmProps().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearVlmProps() {
        internalGetMutableVlmProps().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Volume properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; vlm_props = 4;</code>
       */

      public Builder removeVlmProps(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableVlmProps().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableVlmProps() {
        return internalGetMutableVlmProps().getMutableMap();
      }
      /**
       * <pre>
       * Volume properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; vlm_props = 4;</code>
       */
      public Builder putVlmProps(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableVlmProps().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Volume properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; vlm_props = 4;</code>
       */

      public Builder putAllVlmProps(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableVlmProps().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.linbit.drbdmanage.proto.VlmDfn)
    }

    // @@protoc_insertion_point(class_scope:com.linbit.drbdmanage.proto.VlmDfn)
    private static final com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn();
    }

    public static com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VlmDfn>
        PARSER = new com.google.protobuf.AbstractParser<VlmDfn>() {
      public VlmDfn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new VlmDfn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VlmDfn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VlmDfn> getParserForType() {
      return PARSER;
    }

    public com.linbit.drbdmanage.proto.MsgCrtVlmDfnOuterClass.VlmDfn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_drbdmanage_proto_VlmDfn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_drbdmanage_proto_VlmDfn_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_drbdmanage_proto_VlmDfn_VlmPropsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_drbdmanage_proto_VlmDfn_VlmPropsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MsgCrtVlmDfn.proto\022\033com.linbit.drbdman" +
      "age.proto\"Z\n\014MsgCrtVlmDfn\022\020\n\010rsc_name\030\001 " +
      "\001(\t\0228\n\013vlm_dfn_map\030\002 \003(\0132#.com.linbit.dr" +
      "bdmanage.proto.VlmDfn\"\264\001\n\006VlmDfn\022\016\n\006vlm_" +
      "nr\030\001 \001(\021\022\020\n\010vlm_size\030\002 \001(\003\022\021\n\tvlm_minor\030" +
      "\003 \001(\021\022D\n\tvlm_props\030\004 \003(\01321.com.linbit.dr" +
      "bdmanage.proto.VlmDfn.VlmPropsEntry\032/\n\rV" +
      "lmPropsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_drbdmanage_proto_MsgCrtVlmDfn_descriptor,
        new java.lang.String[] { "RscName", "VlmDfnMap", });
    internal_static_com_linbit_drbdmanage_proto_VlmDfn_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_linbit_drbdmanage_proto_VlmDfn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_drbdmanage_proto_VlmDfn_descriptor,
        new java.lang.String[] { "VlmNr", "VlmSize", "VlmMinor", "VlmProps", });
    internal_static_com_linbit_drbdmanage_proto_VlmDfn_VlmPropsEntry_descriptor =
      internal_static_com_linbit_drbdmanage_proto_VlmDfn_descriptor.getNestedTypes().get(0);
    internal_static_com_linbit_drbdmanage_proto_VlmDfn_VlmPropsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_drbdmanage_proto_VlmDfn_VlmPropsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
