// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgCrtRsc.proto

package com.linbit.drbdmanage.proto;

public final class MsgCrtRscOuterClass {
  private MsgCrtRscOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgCrtRscOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.linbit.drbdmanage.proto.MsgCrtRsc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     */
    java.lang.String getNodeName();
    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNodeNameBytes();

    /**
     * <pre>
     * Resource name
     * </pre>
     *
     * <code>string rsc_name = 2;</code>
     */
    java.lang.String getRscName();
    /**
     * <pre>
     * Resource name
     * </pre>
     *
     * <code>string rsc_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getRscNameBytes();

    /**
     * <pre>
     * Node id
     * </pre>
     *
     * <code>sint32 node_id = 3;</code>
     */
    int getNodeId();

    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */
    int getRscPropsCount();
    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */
    boolean containsRscProps(
        java.lang.String key);
    /**
     * Use {@link #getRscPropsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getRscProps();
    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getRscPropsMap();
    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */

    java.lang.String getRscPropsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */

    java.lang.String getRscPropsOrThrow(
        java.lang.String key);

    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm> 
        getVlmsList();
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm getVlms(int index);
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    int getVlmsCount();
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    java.util.List<? extends com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder> 
        getVlmsOrBuilderList();
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder getVlmsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * drbdmanageNG - Create resource 
   * </pre>
   *
   * Protobuf type {@code com.linbit.drbdmanage.proto.MsgCrtRsc}
   */
  public  static final class MsgCrtRsc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.linbit.drbdmanage.proto.MsgCrtRsc)
      MsgCrtRscOrBuilder {
    // Use MsgCrtRsc.newBuilder() to construct.
    private MsgCrtRsc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgCrtRsc() {
      nodeName_ = "";
      rscName_ = "";
      nodeId_ = 0;
      vlms_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MsgCrtRsc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              rscName_ = s;
              break;
            }
            case 24: {

              nodeId_ = input.readSInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                rscProps_ = com.google.protobuf.MapField.newMapField(
                    RscPropsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              rscProps__ = input.readMessage(
                  RscPropsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              rscProps_.getMutableMap().put(
                  rscProps__.getKey(), rscProps__.getValue());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                vlms_ = new java.util.ArrayList<com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm>();
                mutable_bitField0_ |= 0x00000010;
              }
              vlms_.add(
                  input.readMessage(com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          vlms_ = java.util.Collections.unmodifiableList(vlms_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetRscProps();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc.class, com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc.Builder.class);
    }

    private int bitField0_;
    public static final int NODE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nodeName_;
    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     */
    public java.lang.String getNodeName() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Node name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeNameBytes() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RSC_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object rscName_;
    /**
     * <pre>
     * Resource name
     * </pre>
     *
     * <code>string rsc_name = 2;</code>
     */
    public java.lang.String getRscName() {
      java.lang.Object ref = rscName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rscName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Resource name
     * </pre>
     *
     * <code>string rsc_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRscNameBytes() {
      java.lang.Object ref = rscName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rscName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_ID_FIELD_NUMBER = 3;
    private int nodeId_;
    /**
     * <pre>
     * Node id
     * </pre>
     *
     * <code>sint32 node_id = 3;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }

    public static final int RSC_PROPS_FIELD_NUMBER = 4;
    private static final class RscPropsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_RscPropsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> rscProps_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetRscProps() {
      if (rscProps_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RscPropsDefaultEntryHolder.defaultEntry);
      }
      return rscProps_;
    }

    public int getRscPropsCount() {
      return internalGetRscProps().getMap().size();
    }
    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */

    public boolean containsRscProps(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetRscProps().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRscPropsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getRscProps() {
      return getRscPropsMap();
    }
    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getRscPropsMap() {
      return internalGetRscProps().getMap();
    }
    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */

    public java.lang.String getRscPropsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetRscProps().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Resource properties map
     * </pre>
     *
     * <code>map&lt;string, string&gt; rsc_props = 4;</code>
     */

    public java.lang.String getRscPropsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetRscProps().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int VLMS_FIELD_NUMBER = 5;
    private java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm> vlms_;
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    public java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm> getVlmsList() {
      return vlms_;
    }
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    public java.util.List<? extends com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder> 
        getVlmsOrBuilderList() {
      return vlms_;
    }
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    public int getVlmsCount() {
      return vlms_.size();
    }
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    public com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm getVlms(int index) {
      return vlms_.get(index);
    }
    /**
     * <pre>
     * Volume 
     * </pre>
     *
     * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
     */
    public com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder getVlmsOrBuilder(
        int index) {
      return vlms_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNodeNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeName_);
      }
      if (!getRscNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rscName_);
      }
      if (nodeId_ != 0) {
        output.writeSInt32(3, nodeId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetRscProps(),
          RscPropsDefaultEntryHolder.defaultEntry,
          4);
      for (int i = 0; i < vlms_.size(); i++) {
        output.writeMessage(5, vlms_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNodeNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeName_);
      }
      if (!getRscNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rscName_);
      }
      if (nodeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, nodeId_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetRscProps().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        rscProps__ = RscPropsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, rscProps__);
      }
      for (int i = 0; i < vlms_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, vlms_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc)) {
        return super.equals(obj);
      }
      com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc other = (com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc) obj;

      boolean result = true;
      result = result && getNodeName()
          .equals(other.getNodeName());
      result = result && getRscName()
          .equals(other.getRscName());
      result = result && (getNodeId()
          == other.getNodeId());
      result = result && internalGetRscProps().equals(
          other.internalGetRscProps());
      result = result && getVlmsList()
          .equals(other.getVlmsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getNodeName().hashCode();
      hash = (37 * hash) + RSC_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getRscName().hashCode();
      hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId();
      if (!internalGetRscProps().getMap().isEmpty()) {
        hash = (37 * hash) + RSC_PROPS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetRscProps().hashCode();
      }
      if (getVlmsCount() > 0) {
        hash = (37 * hash) + VLMS_FIELD_NUMBER;
        hash = (53 * hash) + getVlmsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * drbdmanageNG - Create resource 
     * </pre>
     *
     * Protobuf type {@code com.linbit.drbdmanage.proto.MsgCrtRsc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.linbit.drbdmanage.proto.MsgCrtRsc)
        com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRscOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetRscProps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableRscProps();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc.class, com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc.Builder.class);
      }

      // Construct using com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVlmsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        nodeName_ = "";

        rscName_ = "";

        nodeId_ = 0;

        internalGetMutableRscProps().clear();
        if (vlmsBuilder_ == null) {
          vlms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          vlmsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_descriptor;
      }

      public com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc getDefaultInstanceForType() {
        return com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc.getDefaultInstance();
      }

      public com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc build() {
        com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc buildPartial() {
        com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc result = new com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.nodeName_ = nodeName_;
        result.rscName_ = rscName_;
        result.nodeId_ = nodeId_;
        result.rscProps_ = internalGetRscProps();
        result.rscProps_.makeImmutable();
        if (vlmsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            vlms_ = java.util.Collections.unmodifiableList(vlms_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.vlms_ = vlms_;
        } else {
          result.vlms_ = vlmsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc) {
          return mergeFrom((com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc other) {
        if (other == com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc.getDefaultInstance()) return this;
        if (!other.getNodeName().isEmpty()) {
          nodeName_ = other.nodeName_;
          onChanged();
        }
        if (!other.getRscName().isEmpty()) {
          rscName_ = other.rscName_;
          onChanged();
        }
        if (other.getNodeId() != 0) {
          setNodeId(other.getNodeId());
        }
        internalGetMutableRscProps().mergeFrom(
            other.internalGetRscProps());
        if (vlmsBuilder_ == null) {
          if (!other.vlms_.isEmpty()) {
            if (vlms_.isEmpty()) {
              vlms_ = other.vlms_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureVlmsIsMutable();
              vlms_.addAll(other.vlms_);
            }
            onChanged();
          }
        } else {
          if (!other.vlms_.isEmpty()) {
            if (vlmsBuilder_.isEmpty()) {
              vlmsBuilder_.dispose();
              vlmsBuilder_ = null;
              vlms_ = other.vlms_;
              bitField0_ = (bitField0_ & ~0x00000010);
              vlmsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVlmsFieldBuilder() : null;
            } else {
              vlmsBuilder_.addAllMessages(other.vlms_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeName_ = "";
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>string node_name = 1;</code>
       */
      public java.lang.String getNodeName() {
        java.lang.Object ref = nodeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>string node_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNodeNameBytes() {
        java.lang.Object ref = nodeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>string node_name = 1;</code>
       */
      public Builder setNodeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>string node_name = 1;</code>
       */
      public Builder clearNodeName() {
        
        nodeName_ = getDefaultInstance().getNodeName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node name
       * </pre>
       *
       * <code>string node_name = 1;</code>
       */
      public Builder setNodeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rscName_ = "";
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 2;</code>
       */
      public java.lang.String getRscName() {
        java.lang.Object ref = rscName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rscName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRscNameBytes() {
        java.lang.Object ref = rscName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rscName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 2;</code>
       */
      public Builder setRscName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rscName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 2;</code>
       */
      public Builder clearRscName() {
        
        rscName_ = getDefaultInstance().getRscName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Resource name
       * </pre>
       *
       * <code>string rsc_name = 2;</code>
       */
      public Builder setRscNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rscName_ = value;
        onChanged();
        return this;
      }

      private int nodeId_ ;
      /**
       * <pre>
       * Node id
       * </pre>
       *
       * <code>sint32 node_id = 3;</code>
       */
      public int getNodeId() {
        return nodeId_;
      }
      /**
       * <pre>
       * Node id
       * </pre>
       *
       * <code>sint32 node_id = 3;</code>
       */
      public Builder setNodeId(int value) {
        
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node id
       * </pre>
       *
       * <code>sint32 node_id = 3;</code>
       */
      public Builder clearNodeId() {
        
        nodeId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> rscProps_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetRscProps() {
        if (rscProps_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              RscPropsDefaultEntryHolder.defaultEntry);
        }
        return rscProps_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableRscProps() {
        onChanged();;
        if (rscProps_ == null) {
          rscProps_ = com.google.protobuf.MapField.newMapField(
              RscPropsDefaultEntryHolder.defaultEntry);
        }
        if (!rscProps_.isMutable()) {
          rscProps_ = rscProps_.copy();
        }
        return rscProps_;
      }

      public int getRscPropsCount() {
        return internalGetRscProps().getMap().size();
      }
      /**
       * <pre>
       * Resource properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; rsc_props = 4;</code>
       */

      public boolean containsRscProps(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetRscProps().getMap().containsKey(key);
      }
      /**
       * Use {@link #getRscPropsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getRscProps() {
        return getRscPropsMap();
      }
      /**
       * <pre>
       * Resource properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; rsc_props = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getRscPropsMap() {
        return internalGetRscProps().getMap();
      }
      /**
       * <pre>
       * Resource properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; rsc_props = 4;</code>
       */

      public java.lang.String getRscPropsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetRscProps().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Resource properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; rsc_props = 4;</code>
       */

      public java.lang.String getRscPropsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetRscProps().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearRscProps() {
        internalGetMutableRscProps().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Resource properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; rsc_props = 4;</code>
       */

      public Builder removeRscProps(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRscProps().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableRscProps() {
        return internalGetMutableRscProps().getMutableMap();
      }
      /**
       * <pre>
       * Resource properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; rsc_props = 4;</code>
       */
      public Builder putRscProps(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRscProps().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Resource properties map
       * </pre>
       *
       * <code>map&lt;string, string&gt; rsc_props = 4;</code>
       */

      public Builder putAllRscProps(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableRscProps().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm> vlms_ =
        java.util.Collections.emptyList();
      private void ensureVlmsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          vlms_ = new java.util.ArrayList<com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm>(vlms_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder> vlmsBuilder_;

      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm> getVlmsList() {
        if (vlmsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vlms_);
        } else {
          return vlmsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public int getVlmsCount() {
        if (vlmsBuilder_ == null) {
          return vlms_.size();
        } else {
          return vlmsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm getVlms(int index) {
        if (vlmsBuilder_ == null) {
          return vlms_.get(index);
        } else {
          return vlmsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder setVlms(
          int index, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm value) {
        if (vlmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVlmsIsMutable();
          vlms_.set(index, value);
          onChanged();
        } else {
          vlmsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder setVlms(
          int index, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder builderForValue) {
        if (vlmsBuilder_ == null) {
          ensureVlmsIsMutable();
          vlms_.set(index, builderForValue.build());
          onChanged();
        } else {
          vlmsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder addVlms(com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm value) {
        if (vlmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVlmsIsMutable();
          vlms_.add(value);
          onChanged();
        } else {
          vlmsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder addVlms(
          int index, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm value) {
        if (vlmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVlmsIsMutable();
          vlms_.add(index, value);
          onChanged();
        } else {
          vlmsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder addVlms(
          com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder builderForValue) {
        if (vlmsBuilder_ == null) {
          ensureVlmsIsMutable();
          vlms_.add(builderForValue.build());
          onChanged();
        } else {
          vlmsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder addVlms(
          int index, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder builderForValue) {
        if (vlmsBuilder_ == null) {
          ensureVlmsIsMutable();
          vlms_.add(index, builderForValue.build());
          onChanged();
        } else {
          vlmsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder addAllVlms(
          java.lang.Iterable<? extends com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm> values) {
        if (vlmsBuilder_ == null) {
          ensureVlmsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vlms_);
          onChanged();
        } else {
          vlmsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder clearVlms() {
        if (vlmsBuilder_ == null) {
          vlms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          vlmsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public Builder removeVlms(int index) {
        if (vlmsBuilder_ == null) {
          ensureVlmsIsMutable();
          vlms_.remove(index);
          onChanged();
        } else {
          vlmsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder getVlmsBuilder(
          int index) {
        return getVlmsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder getVlmsOrBuilder(
          int index) {
        if (vlmsBuilder_ == null) {
          return vlms_.get(index);  } else {
          return vlmsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public java.util.List<? extends com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder> 
           getVlmsOrBuilderList() {
        if (vlmsBuilder_ != null) {
          return vlmsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vlms_);
        }
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder addVlmsBuilder() {
        return getVlmsFieldBuilder().addBuilder(
            com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.getDefaultInstance());
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder addVlmsBuilder(
          int index) {
        return getVlmsFieldBuilder().addBuilder(
            index, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.getDefaultInstance());
      }
      /**
       * <pre>
       * Volume 
       * </pre>
       *
       * <code>repeated .com.linbit.drbdmanage.proto.Vlm vlms = 5;</code>
       */
      public java.util.List<com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder> 
           getVlmsBuilderList() {
        return getVlmsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder> 
          getVlmsFieldBuilder() {
        if (vlmsBuilder_ == null) {
          vlmsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.Vlm.Builder, com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.VlmOrBuilder>(
                  vlms_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          vlms_ = null;
        }
        return vlmsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.linbit.drbdmanage.proto.MsgCrtRsc)
    }

    // @@protoc_insertion_point(class_scope:com.linbit.drbdmanage.proto.MsgCrtRsc)
    private static final com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc();
    }

    public static com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgCrtRsc>
        PARSER = new com.google.protobuf.AbstractParser<MsgCrtRsc>() {
      public MsgCrtRsc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgCrtRsc(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgCrtRsc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgCrtRsc> getParserForType() {
      return PARSER;
    }

    public com.linbit.drbdmanage.proto.MsgCrtRscOuterClass.MsgCrtRsc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_RscPropsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_RscPropsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MsgCrtRsc.proto\022\033com.linbit.drbdmanage" +
      ".proto\032\017MsgCrtVlm.proto\"\353\001\n\tMsgCrtRsc\022\021\n" +
      "\tnode_name\030\001 \001(\t\022\020\n\010rsc_name\030\002 \001(\t\022\017\n\007no" +
      "de_id\030\003 \001(\021\022G\n\trsc_props\030\004 \003(\01324.com.lin" +
      "bit.drbdmanage.proto.MsgCrtRsc.RscPropsE" +
      "ntry\022.\n\004vlms\030\005 \003(\0132 .com.linbit.drbdmana" +
      "ge.proto.Vlm\032/\n\rRscPropsEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_descriptor,
        new java.lang.String[] { "NodeName", "RscName", "NodeId", "RscProps", "Vlms", });
    internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_RscPropsEntry_descriptor =
      internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_descriptor.getNestedTypes().get(0);
    internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_RscPropsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_drbdmanage_proto_MsgCrtRsc_RscPropsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.linbit.drbdmanage.proto.MsgCrtVlmOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
