// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgLgcTqReply.proto

package com.linbit.drbdmanage.proto;

public final class MsgLgcTqReplyOuterClass {
  private MsgLgcTqReplyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgLgcTqReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.linbit.drbdmanage.proto.MsgLgcTqReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Text query output
     * </pre>
     *
     * <code>repeated string output = 1;</code>
     */
    java.util.List<java.lang.String>
        getOutputList();
    /**
     * <pre>
     * Text query output
     * </pre>
     *
     * <code>repeated string output = 1;</code>
     */
    int getOutputCount();
    /**
     * <pre>
     * Text query output
     * </pre>
     *
     * <code>repeated string output = 1;</code>
     */
    java.lang.String getOutput(int index);
    /**
     * <pre>
     * Text query output
     * </pre>
     *
     * <code>repeated string output = 1;</code>
     */
    com.google.protobuf.ByteString
        getOutputBytes(int index);
  }
  /**
   * <pre>
   * Legacy drbdmanage-1 text query reply
   * </pre>
   *
   * Protobuf type {@code com.linbit.drbdmanage.proto.MsgLgcTqReply}
   */
  public  static final class MsgLgcTqReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.linbit.drbdmanage.proto.MsgLgcTqReply)
      MsgLgcTqReplyOrBuilder {
    // Use MsgLgcTqReply.newBuilder() to construct.
    private MsgLgcTqReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgLgcTqReply() {
      output_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MsgLgcTqReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                output_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              output_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          output_ = output_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply.class, com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply.Builder.class);
    }

    public static final int OUTPUT_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList output_;
    /**
     * <pre>
     * Text query output
     * </pre>
     *
     * <code>repeated string output = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOutputList() {
      return output_;
    }
    /**
     * <pre>
     * Text query output
     * </pre>
     *
     * <code>repeated string output = 1;</code>
     */
    public int getOutputCount() {
      return output_.size();
    }
    /**
     * <pre>
     * Text query output
     * </pre>
     *
     * <code>repeated string output = 1;</code>
     */
    public java.lang.String getOutput(int index) {
      return output_.get(index);
    }
    /**
     * <pre>
     * Text query output
     * </pre>
     *
     * <code>repeated string output = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOutputBytes(int index) {
      return output_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < output_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, output_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < output_.size(); i++) {
          dataSize += computeStringSizeNoTag(output_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOutputList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply)) {
        return super.equals(obj);
      }
      com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply other = (com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply) obj;

      boolean result = true;
      result = result && getOutputList()
          .equals(other.getOutputList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOutputCount() > 0) {
        hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
        hash = (53 * hash) + getOutputList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Legacy drbdmanage-1 text query reply
     * </pre>
     *
     * Protobuf type {@code com.linbit.drbdmanage.proto.MsgLgcTqReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.linbit.drbdmanage.proto.MsgLgcTqReply)
        com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply.class, com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply.Builder.class);
      }

      // Construct using com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        output_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_descriptor;
      }

      public com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply getDefaultInstanceForType() {
        return com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply.getDefaultInstance();
      }

      public com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply build() {
        com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply buildPartial() {
        com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply result = new com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output_ = output_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.output_ = output_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply) {
          return mergeFrom((com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply other) {
        if (other == com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply.getDefaultInstance()) return this;
        if (!other.output_.isEmpty()) {
          if (output_.isEmpty()) {
            output_ = other.output_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOutputIsMutable();
            output_.addAll(other.output_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList output_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOutputIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          output_ = new com.google.protobuf.LazyStringArrayList(output_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getOutputList() {
        return output_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public int getOutputCount() {
        return output_.size();
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public java.lang.String getOutput(int index) {
        return output_.get(index);
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOutputBytes(int index) {
        return output_.getByteString(index);
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public Builder setOutput(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputIsMutable();
        output_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public Builder addOutput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputIsMutable();
        output_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public Builder addAllOutput(
          java.lang.Iterable<java.lang.String> values) {
        ensureOutputIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, output_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public Builder clearOutput() {
        output_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Text query output
       * </pre>
       *
       * <code>repeated string output = 1;</code>
       */
      public Builder addOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureOutputIsMutable();
        output_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.linbit.drbdmanage.proto.MsgLgcTqReply)
    }

    // @@protoc_insertion_point(class_scope:com.linbit.drbdmanage.proto.MsgLgcTqReply)
    private static final com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply();
    }

    public static com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgLgcTqReply>
        PARSER = new com.google.protobuf.AbstractParser<MsgLgcTqReply>() {
      public MsgLgcTqReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgLgcTqReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgLgcTqReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgLgcTqReply> getParserForType() {
      return PARSER;
    }

    public com.linbit.drbdmanage.proto.MsgLgcTqReplyOuterClass.MsgLgcTqReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MsgLgcTqReply.proto\022\033com.linbit.drbdma" +
      "nage.proto\"\037\n\rMsgLgcTqReply\022\016\n\006output\030\001 " +
      "\003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linbit_drbdmanage_proto_MsgLgcTqReply_descriptor,
        new java.lang.String[] { "Output", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
